// Copyright 2026 The Jumpstarter Authors
// (-- api-linter: core::0215::foreign-type-reference=disabled
// (-- api-linter: core::0192::has-comments=disabled
// (-- api-linter: core::0191::java-package=disabled
// (-- api-linter: core::0191::java-outer-classname=disabled
// (-- api-linter: core::0191::java-multiple-files=disabled

// Admin-pipeline-only types. Resource shapes (Lease/Exporter/Client) and
// shared request/response messages live in jumpstarter/v1/resources.proto
// and jumpstarter/v1/requests.proto. Only items that are exclusive to the
// Watch streaming surface remain here.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jumpstarter/admin/v1/common.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType classifies a Watch* stream event. Mirrors Kubernetes
// watch.Event semantics (ADDED, MODIFIED, DELETED, BOOKMARK).
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_ADDED       EventType = 1
	EventType_EVENT_TYPE_MODIFIED    EventType = 2
	EventType_EVENT_TYPE_DELETED     EventType = 3
	// BOOKMARK carries no resource payload, only a resource_version
	// checkpoint. Servers emit bookmarks every ~30s on otherwise idle
	// streams to keep HTTP connections alive across idle timeouts and
	// to give clients a resumable cursor.
	EventType_EVENT_TYPE_BOOKMARK EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_ADDED",
		2: "EVENT_TYPE_MODIFIED",
		3: "EVENT_TYPE_DELETED",
		4: "EVENT_TYPE_BOOKMARK",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_ADDED":       1,
		"EVENT_TYPE_MODIFIED":    2,
		"EVENT_TYPE_DELETED":     3,
		"EVENT_TYPE_BOOKMARK":    4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_jumpstarter_admin_v1_common_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_jumpstarter_admin_v1_common_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_jumpstarter_admin_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_jumpstarter_admin_v1_common_proto protoreflect.FileDescriptor

const file_jumpstarter_admin_v1_common_proto_rawDesc = "" +
	"\n" +
	"!jumpstarter/admin/v1/common.proto\x12\x14jumpstarter.admin.v1*\x87\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10EVENT_TYPE_ADDED\x10\x01\x12\x17\n" +
	"\x13EVENT_TYPE_MODIFIED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x03\x12\x17\n" +
	"\x13EVENT_TYPE_BOOKMARK\x10\x04B\xfb\x01\n" +
	"\x18com.jumpstarter.admin.v1B\vCommonProtoP\x01Z`github.com/jumpstarter-dev/jumpstarter-controller/internal/protocol/jumpstarter/admin/v1;adminv1\xa2\x02\x03JAX\xaa\x02\x14Jumpstarter.Admin.V1\xca\x02\x14Jumpstarter\\Admin\\V1\xe2\x02 Jumpstarter\\Admin\\V1\\GPBMetadata\xea\x02\x16Jumpstarter::Admin::V1b\x06proto3"

var (
	file_jumpstarter_admin_v1_common_proto_rawDescOnce sync.Once
	file_jumpstarter_admin_v1_common_proto_rawDescData []byte
)

func file_jumpstarter_admin_v1_common_proto_rawDescGZIP() []byte {
	file_jumpstarter_admin_v1_common_proto_rawDescOnce.Do(func() {
		file_jumpstarter_admin_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_admin_v1_common_proto_rawDesc), len(file_jumpstarter_admin_v1_common_proto_rawDesc)))
	})
	return file_jumpstarter_admin_v1_common_proto_rawDescData
}

var file_jumpstarter_admin_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jumpstarter_admin_v1_common_proto_goTypes = []any{
	(EventType)(0), // 0: jumpstarter.admin.v1.EventType
}
var file_jumpstarter_admin_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jumpstarter_admin_v1_common_proto_init() }
func file_jumpstarter_admin_v1_common_proto_init() {
	if File_jumpstarter_admin_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_admin_v1_common_proto_rawDesc), len(file_jumpstarter_admin_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jumpstarter_admin_v1_common_proto_goTypes,
		DependencyIndexes: file_jumpstarter_admin_v1_common_proto_depIdxs,
		EnumInfos:         file_jumpstarter_admin_v1_common_proto_enumTypes,
	}.Build()
	File_jumpstarter_admin_v1_common_proto = out.File
	file_jumpstarter_admin_v1_common_proto_goTypes = nil
	file_jumpstarter_admin_v1_common_proto_depIdxs = nil
}
