// Copyright 2026 The Jumpstarter Authors
// (-- api-linter: core::0215::foreign-type-reference=disabled
// (-- api-linter: core::0192::has-comments=disabled
// (-- api-linter: core::0191::java-package=disabled
// (-- api-linter: core::0191::java-outer-classname=disabled
// (-- api-linter: core::0191::java-multiple-files=disabled

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: jumpstarter/admin/v1/lease.proto

package adminv1

import (
	context "context"
	v1 "github.com/jumpstarter-dev/jumpstarter-controller/internal/protocol/jumpstarter/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaseService_GetLease_FullMethodName    = "/jumpstarter.admin.v1.LeaseService/GetLease"
	LeaseService_ListLeases_FullMethodName  = "/jumpstarter.admin.v1.LeaseService/ListLeases"
	LeaseService_CreateLease_FullMethodName = "/jumpstarter.admin.v1.LeaseService/CreateLease"
	LeaseService_UpdateLease_FullMethodName = "/jumpstarter.admin.v1.LeaseService/UpdateLease"
	LeaseService_DeleteLease_FullMethodName = "/jumpstarter.admin.v1.LeaseService/DeleteLease"
	LeaseService_WatchLeases_FullMethodName = "/jumpstarter.admin.v1.LeaseService/WatchLeases"
)

// LeaseServiceClient is the client API for LeaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeaseService administers Lease resources via the admin pipeline
// (multi-issuer OIDC + SAR + Impersonate-*). Every request and response
// type is reused from jumpstarter.v1 so the legacy client.v1 surface and
// this admin surface share one source of truth.
type LeaseServiceClient interface {
	GetLease(ctx context.Context, in *v1.GetRequest, opts ...grpc.CallOption) (*v1.Lease, error)
	ListLeases(ctx context.Context, in *v1.LeaseListRequest, opts ...grpc.CallOption) (*v1.LeaseListResponse, error)
	CreateLease(ctx context.Context, in *v1.LeaseCreateRequest, opts ...grpc.CallOption) (*v1.Lease, error)
	UpdateLease(ctx context.Context, in *v1.LeaseUpdateRequest, opts ...grpc.CallOption) (*v1.Lease, error)
	DeleteLease(ctx context.Context, in *v1.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	WatchLeases(ctx context.Context, in *v1.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error)
}

type leaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaseServiceClient(cc grpc.ClientConnInterface) LeaseServiceClient {
	return &leaseServiceClient{cc}
}

func (c *leaseServiceClient) GetLease(ctx context.Context, in *v1.GetRequest, opts ...grpc.CallOption) (*v1.Lease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Lease)
	err := c.cc.Invoke(ctx, LeaseService_GetLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) ListLeases(ctx context.Context, in *v1.LeaseListRequest, opts ...grpc.CallOption) (*v1.LeaseListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.LeaseListResponse)
	err := c.cc.Invoke(ctx, LeaseService_ListLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) CreateLease(ctx context.Context, in *v1.LeaseCreateRequest, opts ...grpc.CallOption) (*v1.Lease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Lease)
	err := c.cc.Invoke(ctx, LeaseService_CreateLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) UpdateLease(ctx context.Context, in *v1.LeaseUpdateRequest, opts ...grpc.CallOption) (*v1.Lease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Lease)
	err := c.cc.Invoke(ctx, LeaseService_UpdateLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) DeleteLease(ctx context.Context, in *v1.DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LeaseService_DeleteLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaseServiceClient) WatchLeases(ctx context.Context, in *v1.WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeaseService_ServiceDesc.Streams[0], LeaseService_WatchLeases_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[v1.WatchRequest, LeaseEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseService_WatchLeasesClient = grpc.ServerStreamingClient[LeaseEvent]

// LeaseServiceServer is the server API for LeaseService service.
// All implementations must embed UnimplementedLeaseServiceServer
// for forward compatibility.
//
// LeaseService administers Lease resources via the admin pipeline
// (multi-issuer OIDC + SAR + Impersonate-*). Every request and response
// type is reused from jumpstarter.v1 so the legacy client.v1 surface and
// this admin surface share one source of truth.
type LeaseServiceServer interface {
	GetLease(context.Context, *v1.GetRequest) (*v1.Lease, error)
	ListLeases(context.Context, *v1.LeaseListRequest) (*v1.LeaseListResponse, error)
	CreateLease(context.Context, *v1.LeaseCreateRequest) (*v1.Lease, error)
	UpdateLease(context.Context, *v1.LeaseUpdateRequest) (*v1.Lease, error)
	DeleteLease(context.Context, *v1.DeleteRequest) (*emptypb.Empty, error)
	WatchLeases(*v1.WatchRequest, grpc.ServerStreamingServer[LeaseEvent]) error
	mustEmbedUnimplementedLeaseServiceServer()
}

// UnimplementedLeaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaseServiceServer struct{}

func (UnimplementedLeaseServiceServer) GetLease(context.Context, *v1.GetRequest) (*v1.Lease, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLease not implemented")
}
func (UnimplementedLeaseServiceServer) ListLeases(context.Context, *v1.LeaseListRequest) (*v1.LeaseListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeases not implemented")
}
func (UnimplementedLeaseServiceServer) CreateLease(context.Context, *v1.LeaseCreateRequest) (*v1.Lease, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLease not implemented")
}
func (UnimplementedLeaseServiceServer) UpdateLease(context.Context, *v1.LeaseUpdateRequest) (*v1.Lease, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLease not implemented")
}
func (UnimplementedLeaseServiceServer) DeleteLease(context.Context, *v1.DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLease not implemented")
}
func (UnimplementedLeaseServiceServer) WatchLeases(*v1.WatchRequest, grpc.ServerStreamingServer[LeaseEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchLeases not implemented")
}
func (UnimplementedLeaseServiceServer) mustEmbedUnimplementedLeaseServiceServer() {}
func (UnimplementedLeaseServiceServer) testEmbeddedByValue()                      {}

// UnsafeLeaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaseServiceServer will
// result in compilation errors.
type UnsafeLeaseServiceServer interface {
	mustEmbedUnimplementedLeaseServiceServer()
}

func RegisterLeaseServiceServer(s grpc.ServiceRegistrar, srv LeaseServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaseService_ServiceDesc, srv)
}

func _LeaseService_GetLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).GetLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_GetLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).GetLease(ctx, req.(*v1.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_ListLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.LeaseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).ListLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_ListLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).ListLeases(ctx, req.(*v1.LeaseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_CreateLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.LeaseCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).CreateLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_CreateLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).CreateLease(ctx, req.(*v1.LeaseCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_UpdateLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.LeaseUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).UpdateLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_UpdateLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).UpdateLease(ctx, req.(*v1.LeaseUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_DeleteLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaseServiceServer).DeleteLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaseService_DeleteLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaseServiceServer).DeleteLease(ctx, req.(*v1.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaseService_WatchLeases_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeaseServiceServer).WatchLeases(m, &grpc.GenericServerStream[v1.WatchRequest, LeaseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeaseService_WatchLeasesServer = grpc.ServerStreamingServer[LeaseEvent]

// LeaseService_ServiceDesc is the grpc.ServiceDesc for LeaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jumpstarter.admin.v1.LeaseService",
	HandlerType: (*LeaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLease",
			Handler:    _LeaseService_GetLease_Handler,
		},
		{
			MethodName: "ListLeases",
			Handler:    _LeaseService_ListLeases_Handler,
		},
		{
			MethodName: "CreateLease",
			Handler:    _LeaseService_CreateLease_Handler,
		},
		{
			MethodName: "UpdateLease",
			Handler:    _LeaseService_UpdateLease_Handler,
		},
		{
			MethodName: "DeleteLease",
			Handler:    _LeaseService_DeleteLease_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchLeases",
			Handler:       _LeaseService_WatchLeases_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jumpstarter/admin/v1/lease.proto",
}
