[project]
name = "jumpstarter-driver-ssh"
dynamic = ["version", "urls"]
description = "Jumpstarter SSH driver for pure Python SSH connections with authentication and tunneling support"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Kirk Brauer", email = "kirkebrauer@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.6.2.post1",
    "asyncssh>=2.14.0",
    "click>=8.0.0",
    "jumpstarter",
    "jumpstarter-driver-network",
    "jumpstarter-driver-composite",
]

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_ssh"]

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"

[project.entry-points."jumpstarter.drivers"]
SshNetwork = "jumpstarter_driver_ssh.driver:SshNetwork"

[dependency-groups]
dev = ["pytest-cov>=6.0.0", "pytest>=8.3.3", "pytest-anyio>=0.0.0"]
