FROM mcr.microsoft.com/devcontainers/python:1-3.11-bookworm

# Install development dependencies
RUN apt update && apt install -y iperf3 libusb-dev

# Install uv package manager
USER vscode
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
