[project]
name = "jumpstarter-driver-android"
dynamic = ["version", "urls"]
description = ""
authors = [{ name = "Kirk Brauer", email = "kbrauer@hatci.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
    "jumpstarter",
    "jumpstarter-driver-composite",
    "jumpstarter-driver-network",
    "jumpstarter-driver-power",
    "adbutils>=2.8.7",
]

[project.entry-points."jumpstarter.drivers"]
MockPower = "jumpstarter_driver_android.driver:AdbServer"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "trio>=0.28.0"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
