apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: xcp
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  xcp:
    type: jumpstarter_driver_xcp.driver.Xcp
    config:
      transport: ETH
      config_file: /path/to/xcp_config.py
