apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: xcp
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  xcp:
    type: jumpstarter_driver_xcp.driver.Xcp
    config:
      transport: CAN
      can_interface: vector
      channel: 0
      bitrate: 500000
      can_id_master: 2016
      can_id_slave: 2017
