resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/jumpstarter-dev/jumpstarter-operator
  newName: quay.io/jumpstarter-dev/jumpstarter-operator
  newTag: latest
