"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 The Jumpstarter Authors
(-- api-linter: core::0215::foreign-type-reference=disabled
(-- api-linter: core::0192::has-comments=disabled
(-- api-linter: core::0191::java-package=disabled
(-- api-linter: core::0191::java-outer-classname=disabled
(-- api-linter: core::0191::java-multiple-files=disabled
"""

from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
from jumpstarter.client.v1 import client_pb2 as _client_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ClientServiceStub:
    """Client-facing API service for managing exporters and leases."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ClientServiceAsyncStub: ...
    GetExporter: _grpc.UnaryUnaryMultiCallable[_client_pb2.GetExporterRequest, _client_pb2.Exporter]
    """Retrieve a single exporter by resource name."""
    ListExporters: _grpc.UnaryUnaryMultiCallable[_client_pb2.ListExportersRequest, _client_pb2.ListExportersResponse]
    """List exporters in a namespace with optional filtering."""
    GetLease: _grpc.UnaryUnaryMultiCallable[_client_pb2.GetLeaseRequest, _client_pb2.Lease]
    """Retrieve a single lease by resource name."""
    ListLeases: _grpc.UnaryUnaryMultiCallable[_client_pb2.ListLeasesRequest, _client_pb2.ListLeasesResponse]
    """List leases in a namespace with optional filtering."""
    CreateLease: _grpc.UnaryUnaryMultiCallable[_client_pb2.CreateLeaseRequest, _client_pb2.Lease]
    """Create a new lease for an exporter."""
    UpdateLease: _grpc.UnaryUnaryMultiCallable[_client_pb2.UpdateLeaseRequest, _client_pb2.Lease]
    """Update an existing lease."""
    DeleteLease: _grpc.UnaryUnaryMultiCallable[_client_pb2.DeleteLeaseRequest, _empty_pb2.Empty]
    """Delete a lease by resource name."""
    RotateToken: _grpc.UnaryUnaryMultiCallable[_client_pb2.RotateTokenRequest, _client_pb2.RotateTokenResponse]
    """Rotate the authentication token for the client."""

@_typing.type_check_only
class ClientServiceAsyncStub(ClientServiceStub):
    """Client-facing API service for managing exporters and leases."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetExporter: _aio.UnaryUnaryMultiCallable[_client_pb2.GetExporterRequest, _client_pb2.Exporter]  # type: ignore[assignment]
    """Retrieve a single exporter by resource name."""
    ListExporters: _aio.UnaryUnaryMultiCallable[_client_pb2.ListExportersRequest, _client_pb2.ListExportersResponse]  # type: ignore[assignment]
    """List exporters in a namespace with optional filtering."""
    GetLease: _aio.UnaryUnaryMultiCallable[_client_pb2.GetLeaseRequest, _client_pb2.Lease]  # type: ignore[assignment]
    """Retrieve a single lease by resource name."""
    ListLeases: _aio.UnaryUnaryMultiCallable[_client_pb2.ListLeasesRequest, _client_pb2.ListLeasesResponse]  # type: ignore[assignment]
    """List leases in a namespace with optional filtering."""
    CreateLease: _aio.UnaryUnaryMultiCallable[_client_pb2.CreateLeaseRequest, _client_pb2.Lease]  # type: ignore[assignment]
    """Create a new lease for an exporter."""
    UpdateLease: _aio.UnaryUnaryMultiCallable[_client_pb2.UpdateLeaseRequest, _client_pb2.Lease]  # type: ignore[assignment]
    """Update an existing lease."""
    DeleteLease: _aio.UnaryUnaryMultiCallable[_client_pb2.DeleteLeaseRequest, _empty_pb2.Empty]  # type: ignore[assignment]
    """Delete a lease by resource name."""
    RotateToken: _aio.UnaryUnaryMultiCallable[_client_pb2.RotateTokenRequest, _client_pb2.RotateTokenResponse]  # type: ignore[assignment]
    """Rotate the authentication token for the client."""

class ClientServiceServicer(metaclass=_abc_1.ABCMeta):
    """Client-facing API service for managing exporters and leases."""

    @_abc_1.abstractmethod
    def GetExporter(
        self,
        request: _client_pb2.GetExporterRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.Exporter, _abc.Awaitable[_client_pb2.Exporter]]:
        """Retrieve a single exporter by resource name."""

    @_abc_1.abstractmethod
    def ListExporters(
        self,
        request: _client_pb2.ListExportersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.ListExportersResponse, _abc.Awaitable[_client_pb2.ListExportersResponse]]:
        """List exporters in a namespace with optional filtering."""

    @_abc_1.abstractmethod
    def GetLease(
        self,
        request: _client_pb2.GetLeaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.Lease, _abc.Awaitable[_client_pb2.Lease]]:
        """Retrieve a single lease by resource name."""

    @_abc_1.abstractmethod
    def ListLeases(
        self,
        request: _client_pb2.ListLeasesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.ListLeasesResponse, _abc.Awaitable[_client_pb2.ListLeasesResponse]]:
        """List leases in a namespace with optional filtering."""

    @_abc_1.abstractmethod
    def CreateLease(
        self,
        request: _client_pb2.CreateLeaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.Lease, _abc.Awaitable[_client_pb2.Lease]]:
        """Create a new lease for an exporter."""

    @_abc_1.abstractmethod
    def UpdateLease(
        self,
        request: _client_pb2.UpdateLeaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.Lease, _abc.Awaitable[_client_pb2.Lease]]:
        """Update an existing lease."""

    @_abc_1.abstractmethod
    def DeleteLease(
        self,
        request: _client_pb2.DeleteLeaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_empty_pb2.Empty, _abc.Awaitable[_empty_pb2.Empty]]:
        """Delete a lease by resource name."""

    @_abc_1.abstractmethod
    def RotateToken(
        self,
        request: _client_pb2.RotateTokenRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_client_pb2.RotateTokenResponse, _abc.Awaitable[_client_pb2.RotateTokenResponse]]:
        """Rotate the authentication token for the client."""

def add_ClientServiceServicer_to_server(servicer: ClientServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
