[project]
name = "hatch-pin-jumpstarter"
version = "0.1.0"
description = "Hatch plugin that pins jumpstarter packages in the monorepo"
readme = "README.md"
authors = [
    { name = "Nick Cao", email = "nickcao@nichi.co" }
]
requires-python = ">=3.11"
dependencies = [
    "hatchling>=1.27.0",
    "packaging>=24.2",
    "tomli>=2.2.1",
    "tomli-w>=1.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
]

[project.entry-points.hatch]
pin_jumpstarter = "hatch_pin_jumpstarter"
