apiVersion: jumpstarter.dev/v1alpha1
kind: FlashBundleManifest
metadata:
  name: ti-j784s4
spec:
  manufacturer: Texas Instruments
  link: "https://www.ti.com/tool/PROCESSOR-SDK-J784S4"
  bootcmd: "booti 0x82000000 - 0x84000000"
  shelltype: "busybox"
  login:
    login_prompt: "login:"
    username: "root"
    prompt: "#"
  default_target: "usd"
  targets:
    usd: "/sys/class/block#4fb0000"
    emmc: "/sys/class/block#4f80000"
  preflash_commands:
    - "dd if=/dev/zero of=/dev/mmcblk0 bs=512 count=34"
    - "dd if=/dev/zero of=/dev/mmcblk1 bs=512 count=34"
  kernel:
    file: data/J784S4XEVM.flasher.img
    address: "0x82000000"
  dtb:
    default: k3-j784s4-evm
    address: "0x84000000"
    variants:
      k3-j784s4-evm: data/dtbs/k3-j784s4-evm.dtb
