apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  name: dev-jumpstarter-storage-mux-v1
spec:
  proto:
    package: jumpstarter.interfaces.storage_mux.v1
    descriptor: ChFzdG9yYWdlX211eC5wcm90bxIlanVtcHN0YXJ0ZXIuaW50ZXJmYWNlcy5zdG9yYWdlX211eC52MRobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvIhoKC1JlYWRSZXF1ZXN0EgsKA2RzdBgBIAEoCSIbCgxXcml0ZVJlcXVlc3QSCwoDc3JjGAEgASgJMvkCChNTdG9yYWdlTXV4SW50ZXJmYWNlEjkKA0R1dBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgAMAASOgoESG9zdBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgAMAASOQoDT2ZmEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5KAAwABJWCgRSZWFkEjIuanVtcHN0YXJ0ZXIuaW50ZXJmYWNlcy5zdG9yYWdlX211eC52MS5SZWFkUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgAMAASWAoFV3JpdGUSMy5qdW1wc3RhcnRlci5pbnRlcmZhY2VzLnN0b3JhZ2VfbXV4LnYxLldyaXRlUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgAMABK+gIKPwoCBgAaOVN3aXRjaCBzdG9yYWdlIG1lZGlhIGJldHdlZW4gaG9zdCBhbmQgZGV2aWNlIHVuZGVyIHRlc3QuCgo9CgQGAAIAGjVDb25uZWN0IHRoZSBzdG9yYWdlIGRldmljZSB0byB0aGUgZGV2aWNlIHVuZGVyIHRlc3QuCgowCgQGAAIBGihDb25uZWN0IHRoZSBzdG9yYWdlIGRldmljZSB0byB0aGUgaG9zdC4KCj4KBAYAAgIaNkRpc2Nvbm5lY3QgdGhlIHN0b3JhZ2UgZGV2aWNlIGZyb20gYm90aCBob3N0IGFuZCBEVVQuCgo/CgQGAAIDGjdSZWFkIHRoZSBzdG9yYWdlIGRldmljZSBjb250ZW50cyB0byBhIHJlc291cmNlIGhhbmRsZS4KCkUKBAYAAgQaPVdyaXRlIGFuIGltYWdlIGZyb20gYSByZXNvdXJjZSBoYW5kbGUgdG8gdGhlIHN0b3JhZ2UgZGV2aWNlLgpiBnByb3RvMw==
  drivers:
    - language: python
      package: jumpstarter-driver-opendal
      clientClass: "jumpstarter_driver_opendal.client.StorageMuxClient"
      driverClasses:
        - "jumpstarter_driver_opendal.driver:MockStorageMux"
        - "jumpstarter_driver_opendal.driver:MockStorageMuxFlasher"
