apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  name: dev-jumpstarter-corellium-console-v1
spec:
  proto:
    package: jumpstarter.interfaces.corellium_console.v1
    descriptor: Chdjb3JlbGxpdW1fY29uc29sZS5wcm90bxIranVtcHN0YXJ0ZXIuaW50ZXJmYWNlcy5jb3JlbGxpdW1fY29uc29sZS52MTISChBDb3JlbGxpdW1Db25zb2xlSnEKbwoCBgAaaUEgc2VyaWFsIGNvbnNvbGUgZHJpdmVyIHRoYXQgdXNlcyBhIG5ldHdvcmsgd2Vic29ja2V0IHRvIGNvbm5lY3QKdG8gdGhlIHJlbW90ZSB2aXJ0dWFsIGluc3RhbmNlIGNvbnNvbGUuCmIGcHJvdG8z
  drivers:
    - language: python
      package: jumpstarter-driver-corellium
      clientClass: "jumpstarter_driver_pyserial.client.PySerialClient"
