# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: http_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'http_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11http_server.proto\x12%jumpstarter.interfaces.http_server.v1\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0fGetHostResponse\x12\r\n\x05value\x18\x01 \x01(\t\" \n\x0fGetPortResponse\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1f\n\x0eGetUrlResponse\x12\r\n\x05value\x18\x01 \x01(\t2\x8c\x03\n\nHttpServer\x12Y\n\x07GetHost\x12\x16.google.protobuf.Empty\x1a\x36.jumpstarter.interfaces.http_server.v1.GetHostResponse\x12Y\n\x07GetPort\x12\x16.google.protobuf.Empty\x1a\x36.jumpstarter.interfaces.http_server.v1.GetPortResponse\x12W\n\x06GetUrl\x12\x16.google.protobuf.Empty\x1a\x35.jumpstarter.interfaces.http_server.v1.GetUrlResponse\x12\x37\n\x05Start\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x36\n\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'http_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETHOSTRESPONSE']._serialized_start=89
  _globals['_GETHOSTRESPONSE']._serialized_end=121
  _globals['_GETPORTRESPONSE']._serialized_start=123
  _globals['_GETPORTRESPONSE']._serialized_end=155
  _globals['_GETURLRESPONSE']._serialized_start=157
  _globals['_GETURLRESPONSE']._serialized_end=188
  _globals['_HTTPSERVER']._serialized_start=191
  _globals['_HTTPSERVER']._serialized_end=587
# @@protoc_insertion_point(module_scope)
