schemaVersion: 2.3.0
metadata:
  name: jumpstarter-dev
  icon: https://jumpstarter.dev/jumpstarter.svg
  tags:
    - Python
    - UV
    - Jumpstarter
  language: Python
projects:
  - name: jumpstarter
    git:
      remotes:
        origin: https://github.com/rhadp-example-repos/jumpstarter.git
components:
   - name: runtime
     container:
       image: quay.io/rhadp-example-repos/jumpstarter-dev:latest
       mountSources: true

commands:
  - id: sync
    exec:
      component: runtime
      commandLine: make sync
  - id: clean
    exec:
      component: runtime
      commandLine: make clean
  - id: test
    exec:
      component: runtime
      commandLine: make test

