package dev.jumpstarter.examples;

import dev.jumpstarter.devices.ExampleBoardDevice;
import dev.jumpstarter.testing.JumpstarterDevice;
import dev.jumpstarter.testing.JumpstarterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.Iterator;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Example tests for the generated ExampleBoardDevice wrapper.
 *
 * <p>Run with:
 * <pre>
 *   jmp shell --exporter-config exporter.yaml -- ./gradlew :examples-polyglot-java:test
 * </pre>
 *
 * <p>These tests demonstrate the typed device wrapper API generated by {@code jmp codegen}.
 * The {@link JumpstarterExtension} reads {@code JUMPSTARTER_HOST}, creates an
 * {@code ExporterSession}, and injects the typed device via {@code @JumpstarterDevice}.
 */
@ExtendWith(JumpstarterExtension.class)
class ExampleBoardTest {

    @JumpstarterDevice
    ExampleBoardDevice device;

    // -- Power control --

    @Test
    void powerOn() {
        device.power().on();
    }

    @Test
    void powerOff() {
        device.power().off();
    }

    @Test
    void readPowerMeasurements() {
        Iterator<?> readings = device.power().read();
        assertTrue(readings.hasNext(), "Expected at least one power reading");
        Object reading = readings.next();
        assertNotNull(reading);
    }

    // -- Storage mux --

    @Test
    void storageSwitchToHost() {
        device.storage().host();
    }

    @Test
    void storageSwitchToDut() {
        device.storage().dut();
    }

    @Test
    void storageOff() {
        device.storage().off();
    }

    // -- Optional network --

    @Test
    void networkEcho() throws Exception {
        assertNotNull(device.network(), "Expected network driver in this exporter");
        java.net.InetSocketAddress addr = device.network().connectTcp();
        try (java.net.Socket sock = new java.net.Socket(addr.getAddress(), addr.getPort())) {
            sock.getOutputStream().write("hello".getBytes());
            sock.getOutputStream().flush();
            byte[] buf = new byte[5];
            int n = sock.getInputStream().read(buf);
            assertEquals("hello", new String(buf, 0, n));
        } finally {
            device.network().close();
        }
    }
}
