apiVersion: v1
kind: Namespace
metadata:
  name: jumpstarter-windows-e2e
---
apiVersion: operator.jumpstarter.dev/v1alpha1
kind: Jumpstarter
metadata:
  name: jumpstarter
  namespace: jumpstarter-windows-e2e
spec:
  baseDomain: jumpstarter.127.0.0.1.nip.io
  certManager:
    enabled: true
    server:
      selfSigned:
        enabled: true
  authentication:
    internal:
      prefix: "internal:"
      enabled: true
    autoProvisioning:
      enabled: true
  controller:
    image: quay.io/jumpstarter-dev/jumpstarter-controller:0.9.0
    replicas: 1
    grpc:
      endpoints:
        - address: localhost:8082
          nodeport:
            enabled: true
            port: 30010
  routers:
    image: quay.io/jumpstarter-dev/jumpstarter-controller:0.9.0
    replicas: 1
    grpc:
      endpoints:
        - address: localhost:8083
          nodeport:
            enabled: true
            port: 30011
