apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: tftp
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  tftp:
    type: jumpstarter_driver_tftp.driver.Tftp
    config:
      root_dir: /var/lib/tftpboot
      host: 192.168.1.100
      port: 69
      remove_created_on_close: true
