[project]
name = "jumpstarter-all"
dynamic = [
    "version",
    "urls",
]
description = "Jumpstarter meta-package which will install all packages"
authors = [
    { name = "Miguel Angel Ajo", email = "majopela@redhat.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
    "jumpstarter ~= 0.6",
    "jumpstarter-cli ~= 0.6",
    "jumpstarter-cli-admin ~= 0.6",
    "jumpstarter-cli-common ~= 0.6",
    "jumpstarter-cli-driver ~= 0.6",
    "jumpstarter-driver-can ~= 0.6",
    "jumpstarter-driver-composite ~= 0.6",
    "jumpstarter-driver-corellium ~= 0.6",
    "jumpstarter-driver-dutlink ~= 0.6",
    "jumpstarter-driver-flashers ~= 0.6",
    "jumpstarter-driver-http ~= 0.6",
    "jumpstarter-driver-network ~= 0.6",
    "jumpstarter-driver-opendal ~= 0.6",
    "jumpstarter-driver-power ~= 0.6",
    "jumpstarter-driver-probe-rs ~= 0.6",
    "jumpstarter-driver-pyserial ~= 0.6",
    "jumpstarter-driver-qemu ~= 0.6",
    "jumpstarter-driver-raspberrypi ~= 0.6",
    "jumpstarter-driver-sdwire ~= 0.6",
    "jumpstarter-driver-shell ~= 0.6",
    "jumpstarter-driver-snmp ~= 0.6",
    "jumpstarter-driver-tftp ~= 0.6",
    "jumpstarter-driver-uboot ~= 0.6",
    "jumpstarter-driver-ustreamer ~= 0.6",
    "jumpstarter-driver-yepkit ~= 0.6",
    "jumpstarter-imagehash ~= 0.6",
    "jumpstarter-kubernetes ~= 0.6",
    "jumpstarter-protocol ~= 0.6",
    "jumpstarter-testing ~= 0.6",
]

[tool.hatch.build.targets.wheel]
packages = [
    "jumpstarter_all",
]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"
