apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: ssh-mount
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  ssh:
    type: jumpstarter_driver_ssh.driver.SSHWrapper
    config:
      default_username: "root"
      # ssh_identity_file: "/path/to/ssh/key"
    children:
      tcp:
        type: jumpstarter_driver_network.driver.TcpNetwork
        config:
          host: "192.168.1.100"
          port: 22
  mount:
    type: jumpstarter_driver_ssh_mount.driver.SSHMount
    children:
      ssh:
        ref: "ssh"
