apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: stlink-msd
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  flasher:
    type: jumpstarter_driver_stlink_msd.driver.StlinkMsdFlasher
    config: null
