// Copyright 2026 The Jumpstarter Authors
// (-- api-linter: core::0215::foreign-type-reference=disabled
// (-- api-linter: core::0192::has-comments=disabled
// (-- api-linter: core::0191::java-package=disabled
// (-- api-linter: core::0191::java-outer-classname=disabled
// (-- api-linter: core::0191::java-multiple-files=disabled

// Canonical Jumpstarter domain types (Lease, Exporter, Client) and their
// shared helper messages. These messages are referenced by every Jumpstarter
// API surface — the legacy jumpstarter.client.v1 service used by the jmp
// CLI, the new admin.v1 services, and any future surfaces — so there is one
// definitive shape per resource.
//
// Field numbers follow the original jumpstarter.client.v1 layout to keep
// deployed jmp CLI binaries wire-compatible after the resource was hoisted
// out of client.v1. New fields reserved for the admin surface take numbers
// >= 14; older clients ignore them transparently.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jumpstarter/v1/resources.proto

package jumpstarterv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceMetadata bundles the identity-attribution and concurrency-control
// fields the controller stamps onto every Jumpstarter resource. Each domain
// resource embeds this as a field named "metadata" so admin clients see a
// uniform shape across resources.
type ResourceMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display-only username of the OIDC caller that last mutated this
	// resource (mirrored from the jumpstarter.dev/created-by annotation).
	// Optional because resources created by GitOps / kubectl may not carry it.
	CreatedBy *string `protobuf:"bytes,1,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	// OIDC issuer URL of the owner (jumpstarter.dev/owner-issuer annotation).
	OwnerIssuer *string `protobuf:"bytes,2,opt,name=owner_issuer,json=ownerIssuer,proto3,oneof" json:"owner_issuer,omitempty"`
	// Kubernetes resourceVersion. Used by clients for optimistic concurrency
	// and by Watch* RPCs as a resume cursor.
	ResourceVersion string `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// True when the resource is tracked by an external tool (ArgoCD,
	// Flux, Helm, kustomize-controller, …). The controller refuses
	// mutations on these via admin.v1 because edits would be reverted
	// on the next reconciliation; cluster admins can still kubectl-edit.
	// Derived from labels/annotations on every read.
	ExternallyManaged bool `protobuf:"varint,4,opt,name=externally_managed,json=externallyManaged,proto3" json:"externally_managed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResourceMetadata) Reset() {
	*x = ResourceMetadata{}
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetadata) ProtoMessage() {}

func (x *ResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetadata.ProtoReflect.Descriptor instead.
func (*ResourceMetadata) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceMetadata) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *ResourceMetadata) GetOwnerIssuer() string {
	if x != nil && x.OwnerIssuer != nil {
		return *x.OwnerIssuer
	}
	return ""
}

func (x *ResourceMetadata) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ResourceMetadata) GetExternallyManaged() bool {
	if x != nil {
		return x.ExternallyManaged
	}
	return false
}

// Lease is the canonical Jumpstarter Lease resource shape. It mirrors the
// Lease CRD (controller/api/v1alpha1/lease_types.go).
type Lease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Either selector or exporter_name must be set. The combination is
	// intentionally not enforced as REQUIRED here so the message can also
	// carry an empty selector when exporter_name is the chosen pin.
	Selector           string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Duration           *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	EffectiveDuration  *durationpb.Duration   `protobuf:"bytes,4,opt,name=effective_duration,json=effectiveDuration,proto3" json:"effective_duration,omitempty"`
	BeginTime          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=begin_time,json=beginTime,proto3,oneof" json:"begin_time,omitempty"`
	EffectiveBeginTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=effective_begin_time,json=effectiveBeginTime,proto3,oneof" json:"effective_begin_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	EffectiveEndTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=effective_end_time,json=effectiveEndTime,proto3,oneof" json:"effective_end_time,omitempty"`
	Client             *string                `protobuf:"bytes,9,opt,name=client,proto3,oneof" json:"client,omitempty"`
	Exporter           *string                `protobuf:"bytes,10,opt,name=exporter,proto3,oneof" json:"exporter,omitempty"`
	Conditions         []*Condition           `protobuf:"bytes,11,rep,name=conditions,proto3" json:"conditions,omitempty"`
	ExporterName       *string                `protobuf:"bytes,12,opt,name=exporter_name,json=exporterName,proto3,oneof" json:"exporter_name,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Admin-surface extensions. Numbered >= 14 so client.v1 wire format is
	// unchanged for deployed jmp CLI binaries; older clients ignore them.
	Ended  bool              `protobuf:"varint,14,opt,name=ended,proto3" json:"ended,omitempty"`
	Labels map[string]string `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// metadata is populated only by the admin surface; client.v1 callers
	// observe an absent field, which is why it is optional.
	Metadata      *ResourceMetadata `protobuf:"bytes,16,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *Lease) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lease) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *Lease) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Lease) GetEffectiveDuration() *durationpb.Duration {
	if x != nil {
		return x.EffectiveDuration
	}
	return nil
}

func (x *Lease) GetBeginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BeginTime
	}
	return nil
}

func (x *Lease) GetEffectiveBeginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveBeginTime
	}
	return nil
}

func (x *Lease) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Lease) GetEffectiveEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveEndTime
	}
	return nil
}

func (x *Lease) GetClient() string {
	if x != nil && x.Client != nil {
		return *x.Client
	}
	return ""
}

func (x *Lease) GetExporter() string {
	if x != nil && x.Exporter != nil {
		return *x.Exporter
	}
	return ""
}

func (x *Lease) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Lease) GetExporterName() string {
	if x != nil && x.ExporterName != nil {
		return *x.ExporterName
	}
	return ""
}

func (x *Lease) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Lease) GetEnded() bool {
	if x != nil {
		return x.Ended
	}
	return false
}

func (x *Lease) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Lease) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Exporter is the canonical Jumpstarter Exporter resource shape.
type Exporter struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated boolean liveness signal kept for client.v1 wire compatibility.
	// Use status instead.
	//
	// Deprecated: Marked as deprecated in jumpstarter/v1/resources.proto.
	Online        bool           `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Status        ExporterStatus `protobuf:"varint,4,opt,name=status,proto3,enum=jumpstarter.v1.ExporterStatus" json:"status,omitempty"`
	StatusMessage string         `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	// Admin-surface extensions (>= 6 so legacy client.v1 callers don't
	// collide with these new fields). All are optional because the legacy
	// client.v1 surface never populates them and admin Get/List/Watch may
	// also legitimately omit token after the bootstrap secret is rotated.
	Username *string `protobuf:"bytes,6,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Endpoint *string `protobuf:"bytes,7,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	// token is populated only on CreateExporter responses (the bootstrap
	// credential the controller mints inline) and is never echoed on
	// Get/List/Update/Watch.
	Token         *string           `protobuf:"bytes,8,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Metadata      *ResourceMetadata `protobuf:"bytes,9,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exporter) Reset() {
	*x = Exporter{}
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exporter) ProtoMessage() {}

func (x *Exporter) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exporter.ProtoReflect.Descriptor instead.
func (*Exporter) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *Exporter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exporter) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Deprecated: Marked as deprecated in jumpstarter/v1/resources.proto.
func (x *Exporter) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Exporter) GetStatus() ExporterStatus {
	if x != nil {
		return x.Status
	}
	return ExporterStatus_EXPORTER_STATUS_UNSPECIFIED
}

func (x *Exporter) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *Exporter) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Exporter) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *Exporter) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *Exporter) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Client is the canonical Jumpstarter Client resource shape. The Client
// resource was previously not represented in client.v1 — it is added here
// fresh, so field numbering is unconstrained.
type Client struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Labels   map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// All three below are admin-surface only. Optional so a client.v1
	// consumer (or any caller through a path that doesn't populate them)
	// sees them absent rather than as empty strings.
	Endpoint *string `protobuf:"bytes,4,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	// token is populated only on CreateClient responses (the bootstrap
	// credential the controller mints inline) and is never echoed on
	// Get/List/Update/Watch.
	Token    *string           `protobuf:"bytes,5,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Metadata *ResourceMetadata `protobuf:"bytes,6,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// type reflects the authentication mechanism this Client uses:
	// OIDC for auto-provisioned identity Clients (bearer is the OIDC
	// token directly), TOKEN for everything else (admin.v1-created bots,
	// kubectl-applied, legacy). Derived on read from spec.username and
	// the jumpstarter.dev/owner annotation.
	Type          *ClientType `protobuf:"varint,7,opt,name=type,proto3,enum=jumpstarter.v1.ClientType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *Client) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Client) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *Client) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *Client) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Client) GetType() ClientType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ClientType_CLIENT_TYPE_UNSPECIFIED
}

var File_jumpstarter_v1_resources_proto protoreflect.FileDescriptor

const file_jumpstarter_v1_resources_proto_rawDesc = "" +
	"\n" +
	"\x1ejumpstarter/v1/resources.proto\x12\x0ejumpstarter.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bjumpstarter/v1/common.proto\x1a\x1fjumpstarter/v1/kubernetes.proto\"\xec\x01\n" +
	"\x10ResourceMetadata\x12'\n" +
	"\n" +
	"created_by\x18\x01 \x01(\tB\x03\xe0A\x03H\x00R\tcreatedBy\x88\x01\x01\x12+\n" +
	"\fowner_issuer\x18\x02 \x01(\tB\x03\xe0A\x03H\x01R\vownerIssuer\x88\x01\x01\x12.\n" +
	"\x10resource_version\x18\x03 \x01(\tB\x03\xe0A\x03R\x0fresourceVersion\x122\n" +
	"\x12externally_managed\x18\x04 \x01(\bB\x03\xe0A\x03R\x11externallyManagedB\r\n" +
	"\v_created_byB\x0f\n" +
	"\r_owner_issuer\"\x91\n" +
	"\n" +
	"\x05Lease\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1f\n" +
	"\bselector\x18\x02 \x01(\tB\x03\xe0A\x05R\bselector\x12:\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\bduration\x88\x01\x01\x12M\n" +
	"\x12effective_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\x03\xe0A\x03R\x11effectiveDuration\x12>\n" +
	"\n" +
	"begin_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tbeginTime\x88\x01\x01\x12V\n" +
	"\x14effective_begin_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x02R\x12effectiveBeginTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\aendTime\x88\x01\x01\x12R\n" +
	"\x12effective_end_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x04R\x10effectiveEndTime\x88\x01\x01\x12;\n" +
	"\x06client\x18\t \x01(\tB\x1e\xe0A\x03\xfaA\x18\n" +
	"\x16jumpstarter.dev/ClientH\x05R\x06client\x88\x01\x01\x12A\n" +
	"\bexporter\x18\n" +
	" \x01(\tB \xe0A\x03\xfaA\x1a\n" +
	"\x18jumpstarter.dev/ExporterH\x06R\bexporter\x88\x01\x01\x12>\n" +
	"\n" +
	"conditions\x18\v \x03(\v2\x19.jumpstarter.v1.ConditionB\x03\xe0A\x03R\n" +
	"conditions\x12-\n" +
	"\rexporter_name\x18\f \x01(\tB\x03\xe0A\x05H\aR\fexporterName\x88\x01\x01\x128\n" +
	"\x04tags\x18\r \x03(\v2\x1f.jumpstarter.v1.Lease.TagsEntryB\x03\xe0A\x05R\x04tags\x12\x19\n" +
	"\x05ended\x18\x0e \x01(\bB\x03\xe0A\x03R\x05ended\x129\n" +
	"\x06labels\x18\x0f \x03(\v2!.jumpstarter.v1.Lease.LabelsEntryR\x06labels\x12F\n" +
	"\bmetadata\x18\x10 \x01(\v2 .jumpstarter.v1.ResourceMetadataB\x03\xe0A\x03H\bR\bmetadata\x88\x01\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:P\xeaAM\n" +
	"\x15jumpstarter.dev/Lease\x12%namespaces/{namespace}/leases/{lease}*\x06leases2\x05leaseB\v\n" +
	"\t_durationB\r\n" +
	"\v_begin_timeB\x17\n" +
	"\x15_effective_begin_timeB\v\n" +
	"\t_end_timeB\x15\n" +
	"\x13_effective_end_timeB\t\n" +
	"\a_clientB\v\n" +
	"\t_exporterB\x10\n" +
	"\x0e_exporter_nameB\v\n" +
	"\t_metadata\"\xe5\x04\n" +
	"\bExporter\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12<\n" +
	"\x06labels\x18\x02 \x03(\v2$.jumpstarter.v1.Exporter.LabelsEntryR\x06labels\x12\x1d\n" +
	"\x06online\x18\x03 \x01(\bB\x05\xe0A\x03\x18\x01R\x06online\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.jumpstarter.v1.ExporterStatusB\x03\xe0A\x03R\x06status\x12*\n" +
	"\x0estatus_message\x18\x05 \x01(\tB\x03\xe0A\x03R\rstatusMessage\x12\x1f\n" +
	"\busername\x18\x06 \x01(\tH\x00R\busername\x88\x01\x01\x12$\n" +
	"\bendpoint\x18\a \x01(\tB\x03\xe0A\x03H\x01R\bendpoint\x88\x01\x01\x12\x1e\n" +
	"\x05token\x18\b \x01(\tB\x03\xe0A\x03H\x02R\x05token\x88\x01\x01\x12F\n" +
	"\bmetadata\x18\t \x01(\v2 .jumpstarter.v1.ResourceMetadataB\x03\xe0A\x03H\x03R\bmetadata\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:_\xeaA\\\n" +
	"\x18jumpstarter.dev/Exporter\x12+namespaces/{namespace}/exporters/{exporter}*\texporters2\bexporterB\v\n" +
	"\t_usernameB\v\n" +
	"\t_endpointB\b\n" +
	"\x06_tokenB\v\n" +
	"\t_metadata\"\x92\x04\n" +
	"\x06Client\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12:\n" +
	"\x06labels\x18\x03 \x03(\v2\".jumpstarter.v1.Client.LabelsEntryR\x06labels\x12$\n" +
	"\bendpoint\x18\x04 \x01(\tB\x03\xe0A\x03H\x01R\bendpoint\x88\x01\x01\x12\x1e\n" +
	"\x05token\x18\x05 \x01(\tB\x03\xe0A\x03H\x02R\x05token\x88\x01\x01\x12F\n" +
	"\bmetadata\x18\x06 \x01(\v2 .jumpstarter.v1.ResourceMetadataB\x03\xe0A\x03H\x03R\bmetadata\x88\x01\x01\x128\n" +
	"\x04type\x18\a \x01(\x0e2\x1a.jumpstarter.v1.ClientTypeB\x03\xe0A\x03H\x04R\x04type\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:U\xeaAR\n" +
	"\x16jumpstarter.dev/Client\x12'namespaces/{namespace}/clients/{client}*\aclients2\x06clientB\v\n" +
	"\t_usernameB\v\n" +
	"\t_endpointB\b\n" +
	"\x06_tokenB\v\n" +
	"\t_metadataB\a\n" +
	"\x05_typeB\xdf\x01\n" +
	"\x12com.jumpstarter.v1B\x0eResourcesProtoP\x01Z`github.com/jumpstarter-dev/jumpstarter-controller/internal/protocol/jumpstarter/v1;jumpstarterv1\xa2\x02\x03JXX\xaa\x02\x0eJumpstarter.V1\xca\x02\x0eJumpstarter\\V1\xe2\x02\x1aJumpstarter\\V1\\GPBMetadata\xea\x02\x0fJumpstarter::V1b\x06proto3"

var (
	file_jumpstarter_v1_resources_proto_rawDescOnce sync.Once
	file_jumpstarter_v1_resources_proto_rawDescData []byte
)

func file_jumpstarter_v1_resources_proto_rawDescGZIP() []byte {
	file_jumpstarter_v1_resources_proto_rawDescOnce.Do(func() {
		file_jumpstarter_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_resources_proto_rawDesc), len(file_jumpstarter_v1_resources_proto_rawDesc)))
	})
	return file_jumpstarter_v1_resources_proto_rawDescData
}

var file_jumpstarter_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_jumpstarter_v1_resources_proto_goTypes = []any{
	(*ResourceMetadata)(nil),      // 0: jumpstarter.v1.ResourceMetadata
	(*Lease)(nil),                 // 1: jumpstarter.v1.Lease
	(*Exporter)(nil),              // 2: jumpstarter.v1.Exporter
	(*Client)(nil),                // 3: jumpstarter.v1.Client
	nil,                           // 4: jumpstarter.v1.Lease.TagsEntry
	nil,                           // 5: jumpstarter.v1.Lease.LabelsEntry
	nil,                           // 6: jumpstarter.v1.Exporter.LabelsEntry
	nil,                           // 7: jumpstarter.v1.Client.LabelsEntry
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*Condition)(nil),             // 10: jumpstarter.v1.Condition
	(ExporterStatus)(0),           // 11: jumpstarter.v1.ExporterStatus
	(ClientType)(0),               // 12: jumpstarter.v1.ClientType
}
var file_jumpstarter_v1_resources_proto_depIdxs = []int32{
	8,  // 0: jumpstarter.v1.Lease.duration:type_name -> google.protobuf.Duration
	8,  // 1: jumpstarter.v1.Lease.effective_duration:type_name -> google.protobuf.Duration
	9,  // 2: jumpstarter.v1.Lease.begin_time:type_name -> google.protobuf.Timestamp
	9,  // 3: jumpstarter.v1.Lease.effective_begin_time:type_name -> google.protobuf.Timestamp
	9,  // 4: jumpstarter.v1.Lease.end_time:type_name -> google.protobuf.Timestamp
	9,  // 5: jumpstarter.v1.Lease.effective_end_time:type_name -> google.protobuf.Timestamp
	10, // 6: jumpstarter.v1.Lease.conditions:type_name -> jumpstarter.v1.Condition
	4,  // 7: jumpstarter.v1.Lease.tags:type_name -> jumpstarter.v1.Lease.TagsEntry
	5,  // 8: jumpstarter.v1.Lease.labels:type_name -> jumpstarter.v1.Lease.LabelsEntry
	0,  // 9: jumpstarter.v1.Lease.metadata:type_name -> jumpstarter.v1.ResourceMetadata
	6,  // 10: jumpstarter.v1.Exporter.labels:type_name -> jumpstarter.v1.Exporter.LabelsEntry
	11, // 11: jumpstarter.v1.Exporter.status:type_name -> jumpstarter.v1.ExporterStatus
	0,  // 12: jumpstarter.v1.Exporter.metadata:type_name -> jumpstarter.v1.ResourceMetadata
	7,  // 13: jumpstarter.v1.Client.labels:type_name -> jumpstarter.v1.Client.LabelsEntry
	0,  // 14: jumpstarter.v1.Client.metadata:type_name -> jumpstarter.v1.ResourceMetadata
	12, // 15: jumpstarter.v1.Client.type:type_name -> jumpstarter.v1.ClientType
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_jumpstarter_v1_resources_proto_init() }
func file_jumpstarter_v1_resources_proto_init() {
	if File_jumpstarter_v1_resources_proto != nil {
		return
	}
	file_jumpstarter_v1_common_proto_init()
	file_jumpstarter_v1_kubernetes_proto_init()
	file_jumpstarter_v1_resources_proto_msgTypes[0].OneofWrappers = []any{}
	file_jumpstarter_v1_resources_proto_msgTypes[1].OneofWrappers = []any{}
	file_jumpstarter_v1_resources_proto_msgTypes[2].OneofWrappers = []any{}
	file_jumpstarter_v1_resources_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_resources_proto_rawDesc), len(file_jumpstarter_v1_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jumpstarter_v1_resources_proto_goTypes,
		DependencyIndexes: file_jumpstarter_v1_resources_proto_depIdxs,
		MessageInfos:      file_jumpstarter_v1_resources_proto_msgTypes,
	}.Build()
	File_jumpstarter_v1_resources_proto = out.File
	file_jumpstarter_v1_resources_proto_goTypes = nil
	file_jumpstarter_v1_resources_proto_depIdxs = nil
}
