// Copyright 2024 The Jumpstarter Authors

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jumpstarter/v1/router.proto

package jumpstarterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FrameType int32

const (
	FrameType_FRAME_TYPE_DATA       FrameType = 0
	FrameType_FRAME_TYPE_RST_STREAM FrameType = 3
	FrameType_FRAME_TYPE_PING       FrameType = 6
	FrameType_FRAME_TYPE_GOAWAY     FrameType = 7
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0: "FRAME_TYPE_DATA",
		3: "FRAME_TYPE_RST_STREAM",
		6: "FRAME_TYPE_PING",
		7: "FRAME_TYPE_GOAWAY",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_DATA":       0,
		"FRAME_TYPE_RST_STREAM": 3,
		"FRAME_TYPE_PING":       6,
		"FRAME_TYPE_GOAWAY":     7,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_jumpstarter_v1_router_proto_enumTypes[0].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_jumpstarter_v1_router_proto_enumTypes[0]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_jumpstarter_v1_router_proto_rawDescGZIP(), []int{0}
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	FrameType     FrameType              `protobuf:"varint,2,opt,name=frame_type,json=frameType,proto3,enum=jumpstarter.v1.FrameType" json:"frame_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_jumpstarter_v1_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_router_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamRequest) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_FRAME_TYPE_DATA
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	FrameType     FrameType              `protobuf:"varint,2,opt,name=frame_type,json=frameType,proto3,enum=jumpstarter.v1.FrameType" json:"frame_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_jumpstarter_v1_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_v1_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_v1_router_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamResponse) GetFrameType() FrameType {
	if x != nil {
		return x.FrameType
	}
	return FrameType_FRAME_TYPE_DATA
}

var File_jumpstarter_v1_router_proto protoreflect.FileDescriptor

const file_jumpstarter_v1_router_proto_rawDesc = "" +
	"\n" +
	"\x1bjumpstarter/v1/router.proto\x12\x0ejumpstarter.v1\"c\n" +
	"\rStreamRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x128\n" +
	"\n" +
	"frame_type\x18\x02 \x01(\x0e2\x19.jumpstarter.v1.FrameTypeR\tframeType\"d\n" +
	"\x0eStreamResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x128\n" +
	"\n" +
	"frame_type\x18\x02 \x01(\x0e2\x19.jumpstarter.v1.FrameTypeR\tframeType*g\n" +
	"\tFrameType\x12\x13\n" +
	"\x0fFRAME_TYPE_DATA\x10\x00\x12\x19\n" +
	"\x15FRAME_TYPE_RST_STREAM\x10\x03\x12\x13\n" +
	"\x0fFRAME_TYPE_PING\x10\x06\x12\x15\n" +
	"\x11FRAME_TYPE_GOAWAY\x10\a2\\\n" +
	"\rRouterService\x12K\n" +
	"\x06Stream\x12\x1d.jumpstarter.v1.StreamRequest\x1a\x1e.jumpstarter.v1.StreamResponse(\x010\x01B\xdc\x01\n" +
	"\x12com.jumpstarter.v1B\vRouterProtoP\x01Z`github.com/jumpstarter-dev/jumpstarter-controller/internal/protocol/jumpstarter/v1;jumpstarterv1\xa2\x02\x03JXX\xaa\x02\x0eJumpstarter.V1\xca\x02\x0eJumpstarter\\V1\xe2\x02\x1aJumpstarter\\V1\\GPBMetadata\xea\x02\x0fJumpstarter::V1b\x06proto3"

var (
	file_jumpstarter_v1_router_proto_rawDescOnce sync.Once
	file_jumpstarter_v1_router_proto_rawDescData []byte
)

func file_jumpstarter_v1_router_proto_rawDescGZIP() []byte {
	file_jumpstarter_v1_router_proto_rawDescOnce.Do(func() {
		file_jumpstarter_v1_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_router_proto_rawDesc), len(file_jumpstarter_v1_router_proto_rawDesc)))
	})
	return file_jumpstarter_v1_router_proto_rawDescData
}

var file_jumpstarter_v1_router_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jumpstarter_v1_router_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jumpstarter_v1_router_proto_goTypes = []any{
	(FrameType)(0),         // 0: jumpstarter.v1.FrameType
	(*StreamRequest)(nil),  // 1: jumpstarter.v1.StreamRequest
	(*StreamResponse)(nil), // 2: jumpstarter.v1.StreamResponse
}
var file_jumpstarter_v1_router_proto_depIdxs = []int32{
	0, // 0: jumpstarter.v1.StreamRequest.frame_type:type_name -> jumpstarter.v1.FrameType
	0, // 1: jumpstarter.v1.StreamResponse.frame_type:type_name -> jumpstarter.v1.FrameType
	1, // 2: jumpstarter.v1.RouterService.Stream:input_type -> jumpstarter.v1.StreamRequest
	2, // 3: jumpstarter.v1.RouterService.Stream:output_type -> jumpstarter.v1.StreamResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jumpstarter_v1_router_proto_init() }
func file_jumpstarter_v1_router_proto_init() {
	if File_jumpstarter_v1_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_v1_router_proto_rawDesc), len(file_jumpstarter_v1_router_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jumpstarter_v1_router_proto_goTypes,
		DependencyIndexes: file_jumpstarter_v1_router_proto_depIdxs,
		EnumInfos:         file_jumpstarter_v1_router_proto_enumTypes,
		MessageInfos:      file_jumpstarter_v1_router_proto_msgTypes,
	}.Build()
	File_jumpstarter_v1_router_proto = out.File
	file_jumpstarter_v1_router_proto_goTypes = nil
	file_jumpstarter_v1_router_proto_depIdxs = nil
}
