[project]
name = "jumpstarter-driver-tmt"
dynamic = ["version", "dependencies"]
description = "Add your description here"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Miguel Angel Ajo Pelayo", email = "miguelangel@ajo.es" }
]
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter=={{ version }}",
    "jumpstarter-driver-network=={{ version }}",
    "jumpstarter-driver-composite=={{ version }}",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.pytest.ini_options]
addopts = ""
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_tmt"]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
]
