apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: ustreamer
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  ustreamer:
    type: jumpstarter_driver_ustreamer.driver.UStreamer
    config:
      executable: ustreamer
      args:
        brightness: auto
        contrast: default
