"""Build hook: generate the proto-first Python modules from the committed interface proto.

The `.proto` (interfaces/proto/jumpstarter/interfaces/power/v1/power.proto) is the source of
truth; the typed modules derived from it — the message dataclasses, the driver interface base, the
typed client, and the embedded descriptor — are BUILD ARTIFACTS, regenerated into the gitignored
``jumpstarter_driver_power/_generated/`` package on every wheel/editable build (the Python analog
of the Rust crates' build.rs → OUT_DIR and the JVM's generateProto → build/generated). A proto
change regenerates them, and an impl that no longer satisfies the new signatures breaks the build —
intentionally.

Also runnable standalone for the edit loop (editable installs don't re-run build hooks):

    uv run python hatch_build.py
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

PACKAGE_DIR = Path(__file__).parent
REPO_ROOT = PACKAGE_DIR.parents[2]
PROTO = REPO_ROOT / "interfaces" / "proto" / "jumpstarter" / "interfaces" / "power" / "v1" / "power.proto"
INCLUDE = REPO_ROOT / "interfaces" / "proto"
OUT = PACKAGE_DIR / "jumpstarter_driver_power" / "_generated"
PYTHON_PACKAGE = "jumpstarter_driver_power._generated"


def generate() -> None:
    """Run jumpstarter-codegen (driver base + typed client) into the _generated package."""
    OUT.mkdir(parents=True, exist_ok=True)
    for kind in ("stub", "client"):
        subprocess.run(
            [
                "cargo", "run", "-q", "-p", "jumpstarter-codegen", "--bin", "jumpstarter-codegen",
                "--",
                "--proto", str(PROTO),
                "-I", str(INCLUDE),
                "--language", "python",
                "--kind", kind,
                "--python-package", PYTHON_PACKAGE,
                "--out", str(OUT),
            ],
            cwd=REPO_ROOT / "rust",
            check=True,
        )
    (OUT / "__init__.py").write_text(
        "# @generated by jumpstarter-codegen (see hatch_build.py). DO NOT EDIT.\n"
    )


try:
    from hatchling.builders.hooks.plugin.interface import BuildHookInterface
except ImportError:  # standalone `python hatch_build.py` run — hatchling not needed
    BuildHookInterface = object


class JumpstarterCodegenHook(BuildHookInterface):
    """Regenerate ``_generated/`` from the committed proto at build time."""

    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        if not PROTO.exists() or shutil.which("cargo") is None:
            # Building outside the monorepo (e.g. from an sdist): the generated modules must
            # already be present — regeneration needs the repo's proto + the Rust codegen.
            if (OUT / "__init__.py").exists():
                self.app.display_warning(
                    "jumpstarter codegen skipped (no repo proto/cargo); keeping existing _generated/"
                )
            else:
                raise RuntimeError(
                    "cannot generate jumpstarter_driver_power._generated: needs the monorepo's "
                    f"{PROTO} and cargo on PATH (or pre-generated modules)"
                )
        else:
            generate()
        # _generated/ is gitignored; hatchling excludes gitignored files unless declared artifacts.
        build_data.setdefault("artifacts", []).append("jumpstarter_driver_power/_generated/*.py")


if __name__ == "__main__":
    generate()
    print(f"generated {PYTHON_PACKAGE} from {PROTO.relative_to(REPO_ROOT)}")
