apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: can
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  can:
    type: jumpstarter_driver_can.IsoTpPython
    config:
      channel: 0
      interface: virtual
      address:
        rxid: 1
        txid: 2
      params:
        max_frame_size: 2048
        blocking_send: false
        can_fd: true
