apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: someip
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  someip:
    type: jumpstarter_driver_someip.driver.SomeIp
    config:
      host: 192.168.100.1
      port: 30490
      transport_mode: UDP
      remote_host: 192.168.100.10
      remote_port: 30490
