# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ssh_wrapper.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ssh_wrapper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ssh_wrapper.proto\x12%jumpstarter.interfaces.ssh_wrapper.v1\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x1aGetDefaultUsernameResponse\x12\r\n\x05value\x18\x01 \x01(\t\"&\n\x15GetSshCommandResponse\x12\r\n\x05value\x18\x01 \x01(\t\"\'\n\x16GetSshIdentityResponse\x12\r\n\x05value\x18\x01 \x01(\t2\xcd\x02\n\nSSHWrapper\x12o\n\x12GetDefaultUsername\x12\x16.google.protobuf.Empty\x1a\x41.jumpstarter.interfaces.ssh_wrapper.v1.GetDefaultUsernameResponse\x12\x65\n\rGetSshCommand\x12\x16.google.protobuf.Empty\x1a<.jumpstarter.interfaces.ssh_wrapper.v1.GetSshCommandResponse\x12g\n\x0eGetSshIdentity\x12\x16.google.protobuf.Empty\x1a=.jumpstarter.interfaces.ssh_wrapper.v1.GetSshIdentityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ssh_wrapper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEFAULTUSERNAMERESPONSE']._serialized_start=89
  _globals['_GETDEFAULTUSERNAMERESPONSE']._serialized_end=132
  _globals['_GETSSHCOMMANDRESPONSE']._serialized_start=134
  _globals['_GETSSHCOMMANDRESPONSE']._serialized_end=172
  _globals['_GETSSHIDENTITYRESPONSE']._serialized_start=174
  _globals['_GETSSHIDENTITYRESPONSE']._serialized_end=213
  _globals['_SSHWRAPPER']._serialized_start=216
  _globals['_SSHWRAPPER']._serialized_end=549
# @@protoc_insertion_point(module_scope)
