[project]
name = "jumpstarter-driver-uboot"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
  "jumpstarter=={{ version }}",
  "jumpstarter-driver-composite=={{ version }}",
  "pexpect>=4.9.0",
]

[dependency-groups]
dev = [
  "jumpstarter-driver-qemu",
  "pytest>=8.3.2",
  "pytest-cov>=5.0.0",
  "requests>=2.32.3",
  "rpmfile>=2.1.0",
  "zstandard>=0.23.0",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv.sources]
jumpstarter-driver-composite = { workspace = true }
jumpstarter-driver-qemu = { workspace = true }

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

