[project]
name = "jumpstarter-driver-gpiod"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = ["jumpstarter=={{ version }}", "jumpstarter-driver-power=={{ version }}", "click>=8.1.7.2", "gpiod; platform_system == 'Linux'"]

[project.entry-points."jumpstarter.drivers"]
DigitalInput = "jumpstarter_driver_gpiod.driver:DigitalInput"
DigitalOutput = "jumpstarter_driver_gpiod.driver:DigitalOutput"
PowerSwitch = "jumpstarter_driver_gpiod.driver:PowerSwitch"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

