[project]
name = "jumpstarter-driver-flashers"
dynamic = [
    "version",
    "urls",
]
description = "Jumpstarter software defined flasher driver"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Benny Zlotnik", email = "bzlotnik@redhat.com" },
    { name = "Miguel Angel Ajo", email = "majopela@redhat.com" },
]
requires-python = ">=3.11"
dependencies = [
    "oras>=0.2.25",
    "anyio>=4.6.2.post1",
    "jumpstarter ~= 0.6",
    "jumpstarter-driver-opendal ~= 0.6",
    "jumpstarter-driver-pyserial ~= 0.6",
    "jumpstarter-driver-http ~= 0.6",
    "jumpstarter-driver-tftp ~= 0.6",
    "jumpstarter-driver-power ~= 0.6",
    "jumpstarter-driver-uboot ~= 0.6",
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = [
    "jumpstarter_driver_flashers",
]

[tool.uv.sources.jumpstarter-driver-uboot]
workspace = true

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
]
