[project]
name = "jumpstarter-cli-admin"
dynamic = ["version", "dependencies"]
description = ""
authors = [{ name = "Kirk Brauer", email = "kbrauer@hatci.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "grpcio-reflection>=1.60.0",
    "jumpstarter-cli-common=={{ version }}",
    "jumpstarter-kubernetes=={{ version }}",
]

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-anyio>=0.0.0",
  "pytest-asyncio>=0.0.0",
  "pytest-cov>=5.0.0",
]

[project.scripts]
jmp-admin = "jumpstarter_cli_admin:admin"

[tool.hatch.build.targets.wheel]
packages = ["jumpstarter_cli_admin"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

