apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: doip
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  doip:
    type: jumpstarter_driver_doip.driver.DoIP
    config:
      ecu_ip: 192.168.1.100
      ecu_logical_address: 224
