[project]
name = "jumpstarter-driver-composite"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = ["jumpstarter=={{ version }}", "click>=8.1.7.2"]

[project.entry-points."jumpstarter.drivers"]
Composite = "jumpstarter_driver_composite.driver:Composite"
Proxy = "jumpstarter_driver_composite.driver:Proxy"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "jumpstarter-driver-power"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

