apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: pyserial
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  ccplex:
    type: jumpstarter_driver_pyserial.nvdemux.driver.NVDemuxSerial
    config:
      demuxer_path: /opt/nvidia/nv_tcu_demuxer
