[project]
name = "jumpstarter-driver-http-power"
dynamic = ["version", "dependencies"]
description = "A power driver for HTTP enabled PDUs or smart sockets, like the Shelly splug"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Miguel Angel Ajo", email = "majopela@redhat.com" }
]
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter=={{ version }}",
    "jumpstarter-driver-power=={{ version }}",
]


[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_http_power"]

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
]
