[project]
name = "jumpstarter-driver-network"
dynamic = ["version", "urls"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
  "jumpstarter",
  "pexpect>=4.9.0",
  "fabric>=3.2.2",
  "wsproto>=1.2.0",
  "asyncclick>=8.1.8",
]

[project.entry-points."jumpstarter.drivers"]
TcpNetwork = "jumpstarter_driver_network.driver:TcpNetwork"
UdpNetwork = "jumpstarter_driver_network.driver:UdpNetwork"
UnixNetwork = "jumpstarter_driver_network.driver:UnixNetwork"
EchoNetwork = "jumpstarter_driver_network.driver:EchoNetwork"

[project.entry-points."jumpstarter.adapters"]
TcpPortforward = "jumpstarter_driver_network.adapters:TcpPortforwardAdapter"
UnixPortforward = "jumpstarter_driver_network.adapters:UnixPortforwardAdapter"
Pexpect = "jumpstarter_driver_network.adapters:PexpectAdapter"
Novnc = "jumpstarter_driver_network.adapters:NovncAdapter"

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-cov>=5.0.0",
  "types-paramiko>=3.5.0.20240928",
  "types-pexpect>=4.9.0.20241208",
  "websocket-client>=1.8.0",
]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
