"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 The Jumpstarter Authors"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _FrameType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FrameTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_FrameType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FRAME_TYPE_DATA: _FrameType.ValueType  # 0
    FRAME_TYPE_RST_STREAM: _FrameType.ValueType  # 3
    FRAME_TYPE_PING: _FrameType.ValueType  # 6
    FRAME_TYPE_GOAWAY: _FrameType.ValueType  # 7

class FrameType(_FrameType, metaclass=_FrameTypeEnumTypeWrapper): ...

FRAME_TYPE_DATA: FrameType.ValueType  # 0
FRAME_TYPE_RST_STREAM: FrameType.ValueType  # 3
FRAME_TYPE_PING: FrameType.ValueType  # 6
FRAME_TYPE_GOAWAY: FrameType.ValueType  # 7
Global___FrameType: typing_extensions.TypeAlias = FrameType

@typing.final
class StreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: builtins.int
    FRAME_TYPE_FIELD_NUMBER: builtins.int
    payload: builtins.bytes
    frame_type: Global___FrameType.ValueType
    def __init__(
        self,
        *,
        payload: builtins.bytes = ...,
        frame_type: Global___FrameType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["frame_type", b"frame_type", "payload", b"payload"]) -> None: ...

Global___StreamRequest: typing_extensions.TypeAlias = StreamRequest

@typing.final
class StreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: builtins.int
    FRAME_TYPE_FIELD_NUMBER: builtins.int
    payload: builtins.bytes
    frame_type: Global___FrameType.ValueType
    def __init__(
        self,
        *,
        payload: builtins.bytes = ...,
        frame_type: Global___FrameType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["frame_type", b"frame_type", "payload", b"payload"]) -> None: ...

Global___StreamResponse: typing_extensions.TypeAlias = StreamResponse
