"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 The Jumpstarter Authors"""

import abc
import collections.abc
import grpc
import grpc.aio
import jumpstarter.v1.router_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_RouterServiceStreamType = typing_extensions.TypeVar(
    '_RouterServiceStreamType',
    grpc.StreamStreamMultiCallable[
        jumpstarter.v1.router_pb2.StreamRequest,
        jumpstarter.v1.router_pb2.StreamResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        jumpstarter.v1.router_pb2.StreamRequest,
        jumpstarter.v1.router_pb2.StreamResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        jumpstarter.v1.router_pb2.StreamRequest,
        jumpstarter.v1.router_pb2.StreamResponse,
    ],
)

class RouterServiceStub(typing.Generic[_RouterServiceStreamType]):
    """StreamService
    Claims:
    iss: jumpstarter controller
    aud: jumpstarter router
    sub: jumpstarter client/exporter
    stream: stream id
    """

    @typing.overload
    def __init__(self: RouterServiceStub[
        grpc.StreamStreamMultiCallable[
            jumpstarter.v1.router_pb2.StreamRequest,
            jumpstarter.v1.router_pb2.StreamResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: RouterServiceStub[
        grpc.aio.StreamStreamMultiCallable[
            jumpstarter.v1.router_pb2.StreamRequest,
            jumpstarter.v1.router_pb2.StreamResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Stream: _RouterServiceStreamType
    """Stream connects caller to another caller of the same stream"""

RouterServiceAsyncStub: typing_extensions.TypeAlias = RouterServiceStub[
    grpc.aio.StreamStreamMultiCallable[
        jumpstarter.v1.router_pb2.StreamRequest,
        jumpstarter.v1.router_pb2.StreamResponse,
    ],
]

class RouterServiceServicer(metaclass=abc.ABCMeta):
    """StreamService
    Claims:
    iss: jumpstarter controller
    aud: jumpstarter router
    sub: jumpstarter client/exporter
    stream: stream id
    """

    @abc.abstractmethod
    def Stream(
        self,
        request_iterator: _MaybeAsyncIterator[jumpstarter.v1.router_pb2.StreamRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[jumpstarter.v1.router_pb2.StreamResponse], collections.abc.AsyncIterator[jumpstarter.v1.router_pb2.StreamResponse]]:
        """Stream connects caller to another caller of the same stream"""

def add_RouterServiceServicer_to_server(servicer: RouterServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
