apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: pi-pico
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  storage:
    type: jumpstarter_driver_pi_pico.driver.PiPicoFlasher
    config: {}
    children:
      serial:
        ref: serial
  serial:
    type: jumpstarter_driver_pyserial.driver.PySerial
    config:
      url: /dev/ttyACM0
      baudrate: 115200
