apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: pi-pico
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  storage:
    type: jumpstarter_driver_pi_pico.driver.PiPicoFlasher
    config: {}
    children:
      serial:
        ref: serial
      bootsel:
        ref: bootsel
      run:
        ref: run
  serial:
    type: jumpstarter_driver_pyserial.driver.PySerial
    config:
      url: /dev/ttyACM0
      baudrate: 115200
  bootsel:
    type: jumpstarter_driver_gpiod.driver.DigitalOutput
    config:
      device: /dev/gpiochip4
      line: 17
      drive: open_drain
      active_low: true
      initial_value: inactive
  run:
    type: jumpstarter_driver_gpiod.driver.DigitalOutput
    config:
      device: /dev/gpiochip4
      line: 27
      drive: open_drain
      active_low: true
      initial_value: inactive
