[project]
name = "jumpstarter-driver-power"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = ["jumpstarter=={{ version }}", "pyserial>=3.5", "click>=8.1.7.2"]

[project.entry-points."jumpstarter.drivers"]
MockPower = "jumpstarter_driver_power.driver:MockPower"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "trio>=0.28.0"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

