# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vnc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vnc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvnc.proto\x12\x1djumpstarter.interfaces.vnc.v1\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x19GetDefaultEncryptResponse\x12\r\n\x05value\x18\x01 \x01(\x08\x32l\n\x03Vnc\x12\x65\n\x11GetDefaultEncrypt\x12\x16.google.protobuf.Empty\x1a\x38.jumpstarter.interfaces.vnc.v1.GetDefaultEncryptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vnc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDEFAULTENCRYPTRESPONSE']._serialized_start=73
  _globals['_GETDEFAULTENCRYPTRESPONSE']._serialized_end=115
  _globals['_VNC']._serialized_start=117
  _globals['_VNC']._serialized_end=225
# @@protoc_insertion_point(module_scope)
