# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage_mux.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'storage_mux.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11storage_mux.proto\x12%jumpstarter.interfaces.storage_mux.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x0bReadRequest\x12\x0b\n\x03\x64st\x18\x01 \x01(\t\"\x1b\n\x0cWriteRequest\x12\x0b\n\x03src\x18\x01 \x01(\t2\xe5\x02\n\x13StorageMuxInterface\x12\x35\n\x03\x44ut\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x36\n\x04Host\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x35\n\x03Off\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12R\n\x04Read\x12\x32.jumpstarter.interfaces.storage_mux.v1.ReadRequest\x1a\x16.google.protobuf.Empty\x12T\n\x05Write\x12\x33.jumpstarter.interfaces.storage_mux.v1.WriteRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_mux_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=89
  _globals['_READREQUEST']._serialized_end=115
  _globals['_WRITEREQUEST']._serialized_start=117
  _globals['_WRITEREQUEST']._serialized_end=144
  _globals['_STORAGEMUXINTERFACE']._serialized_start=147
  _globals['_STORAGEMUXINTERFACE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
