name: 'Jumpstarter end-to-end testing'
inputs:
  controller-ref:
    description: 'jumpstarter-dev/jumpstarter-controller git ref'
    required: true
  jumpstarter-ref:
    description: 'jumpstarter-dev/jumpstarter git ref'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    - name: Install python
      shell: bash
      run: |
        uv python install 3.12
    - name: Checkout jumpstarter controller
      uses: actions/checkout@v4
      with:
        repository: jumpstarter-dev/jumpstarter-controller
        ref: ${{ inputs.controller-ref }}
        path: controller
    - name: Checkout jumpstarter
      uses: actions/checkout@v4
      with:
        repository: jumpstarter-dev/jumpstarter
        ref: ${{ inputs.jumpstarter-ref }}
        path: jumpstarter
    - name: Deploy jumpstarter controller
      shell: bash
      run: |
        make -C controller deploy
    - name: Install jumpstarter
      shell: bash
      run: |
        uv venv
        uv pip install \
          ./jumpstarter/packages/jumpstarter-cli \
          ./jumpstarter/packages/jumpstarter-driver-composite \
          ./jumpstarter/packages/jumpstarter-driver-power \
          ./jumpstarter/packages/jumpstarter-driver-opendal
    - name: Run jumpstarter
      shell: bash
      run: |
        . .venv/bin/activate

        export JUMPSTARTER_GRPC_INSECURE=1

        jmp admin create client   test-client-1   --save --unsafe
        jmp admin create exporter test-exporter-1 --save
        jmp admin create exporter test-exporter-2 --save

        cat <<EOF >> /etc/jumpstarter/exporters/test-exporter-1.yaml
        export:
          power:
            type: jumpstarter_driver_power.driver.MockPower
        EOF

        kubectl -n default patch exporters.jumpstarter.dev test-exporter-1 \
          --type=merge --patch '{"metadata":{"labels":{"example.com/board":"rpi4"}}}'

        cat <<EOF >> /etc/jumpstarter/exporters/test-exporter-2.yaml
        export:
          storage:
            type: jumpstarter_driver_opendal.driver.MockStorageMux
        EOF

        kubectl -n default patch exporters.jumpstarter.dev test-exporter-2 \
          --type=merge --patch '{"metadata":{"labels":{"example.com/board":"rpi5"}}}'

        jmp client list-configs
        jmp exporter list-configs

        jmp exporter run test-exporter-1 &
        jmp exporter run test-exporter-2 &

        sleep 5

        jmp client shell test-client-1 --label example.com/board rpi4 <<EOF
        j power
        EOF

        jmp client shell test-client-1 --label example.com/board rpi5 <<EOF
        j storage
        EOF
