name: 'Jumpstarter end-to-end testing'
inputs:
  controller-ref:
    description: 'jumpstarter-dev/jumpstarter-controller git ref'
    required: true
  jumpstarter-ref:
    description: 'jumpstarter-dev/jumpstarter git ref'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    - name: Install python
      shell: bash
      run: |
        uv python install 3.12
    - name: Checkout jumpstarter controller
      uses: actions/checkout@v4
      with:
        repository: jumpstarter-dev/jumpstarter-controller
        ref: ${{ inputs.controller-ref }}
        path: controller
    - name: Checkout jumpstarter
      uses: actions/checkout@v4
      with:
        repository: jumpstarter-dev/jumpstarter
        ref: ${{ inputs.jumpstarter-ref }}
        path: jumpstarter
    - name: Deploy jumpstarter controller
      shell: bash
      run: |
        cp "$GITHUB_ACTION_PATH"/values.kind.yaml ./controller/deploy/helm/jumpstarter/values.kind.yaml
        cp "$GITHUB_ACTION_PATH"/kind_cluster.yaml ./controller/hack/kind_cluster.yaml
        make -C controller deploy
    - name: Deploy dex
      shell: bash
      run: |
        kubectl create namespace dex
        kubectl apply -f "$GITHUB_ACTION_PATH"/dex.yaml
        helm repo add dex https://charts.dexidp.io
        helm install --namespace dex --wait -f "$GITHUB_ACTION_PATH"/dex.values.yaml dex dex/dex
    - name: Install jumpstarter
      shell: bash
      run: |
        uv venv
        uv pip install \
          ./jumpstarter/packages/jumpstarter-cli \
          ./jumpstarter/packages/jumpstarter-driver-composite \
          ./jumpstarter/packages/jumpstarter-driver-power \
          ./jumpstarter/packages/jumpstarter-driver-opendal
    - name: Run jumpstarter
      shell: bash
      run: |
        sudo cp "$GITHUB_ACTION_PATH"/minica.pem /usr/local/share/ca-certificates/minica.crt
        sudo update-ca-certificates

        echo "127.0.0.1 dex.dex.svc.cluster.local" | sudo tee -a /etc/hosts

        ENDPOINT=$(helm get values jumpstarter --output json | jq -r '."jumpstarter-controller".grpc.endpoint')

        sudo mkdir -p /etc/jumpstarter/exporters
        sudo chown $USER /etc/jumpstarter/exporters

        . .venv/bin/activate

        export JUMPSTARTER_GRPC_INSECURE=1

        jmp admin create client   test-client-oidc     --unsafe --out /dev/null --oidc-username dex:test-client-oidc
        jmp admin create client   test-client-legacy   --unsafe --save
        jmp admin create exporter test-exporter-oidc   --out /dev/null --oidc-username dex:test-exporter-oidc \
          --label example.com/board oidc
        jmp admin create exporter test-exporter-legacy --save \
          --label example.com/board legacy

        jmp client   list-configs
        jmp exporter list-configs

        jmp client   login test-client-oidc \
          --endpoint "$ENDPOINT" --namespace default --name test-client-oidc \
          --issuer https://dex.dex.svc.cluster.local:5556 \
          --username test-client-oidc@example.com --password password --unsafe
        jmp exporter login test-exporter-oidc \
          --endpoint "$ENDPOINT" --namespace default --name test-exporter-oidc \
          --issuer https://dex.dex.svc.cluster.local:5556 \
          --username test-exporter-oidc@example.com --password password

        go run github.com/mikefarah/yq/v4@latest -i ". * load(\"$GITHUB_ACTION_PATH/exporter.yaml\")" \
          /etc/jumpstarter/exporters/test-exporter-oidc.yaml
        go run github.com/mikefarah/yq/v4@latest -i ". * load(\"$GITHUB_ACTION_PATH/exporter.yaml\")" \
          /etc/jumpstarter/exporters/test-exporter-legacy.yaml

        jmp client   list-configs
        jmp exporter list-configs

        jmp exporter run test-exporter-oidc &
        jmp exporter run test-exporter-legacy &

        sleep 5

        jmp client shell test-client-oidc --label example.com/board oidc <<EOF
        j power on
        EOF

        jmp client shell test-client-legacy --label example.com/board legacy <<EOF
        j power on
        EOF
