---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jumpstarter-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients
  - exporterclasses
  - exporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients/finalizers
  - exporterclasses/finalizers
  - exporters/finalizers
  verbs:
  - update
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients/status
  - driverinterfaces/status
  - exporterclasses/status
  - exporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jumpstarter.dev
  resources:
  - driverinterfaces
  - exporteraccesspolicies
  verbs:
  - get
  - list
  - watch
