apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: vnc
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  vnc:
    type: jumpstarter_driver_vnc.driver.Vnc
    default_encrypt: false
    children:
      tcp:
        type: jumpstarter_driver_network.driver.TcpNetwork
        config:
          host: 127.0.0.1
          port: 5901
