[project]
name = "jumpstarter-imagehash"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = ["imagehash>=4.3.1", "jumpstarter=={{ version }}"]

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

