apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: mitmproxy
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  proxy:
    type: jumpstarter_driver_mitmproxy.driver.MitmproxyDriver
    config:
      listen:
        host: 0.0.0.0
        port: 8080
      web:
        host: 0.0.0.0
        port: 8081
      directories:
        data: /opt/jumpstarter/mitmproxy
      ssl_insecure: true
