.PHONY: build test clean

build:
	cd .. && ./gradlew :java:jumpstarter-client:build -x test

test:
	cd .. && ./gradlew :java:jumpstarter-client:test

clean:
	cd .. && ./gradlew :java:jumpstarter-client:clean
