[project]
name = "jumpstarter-driver-ridesx"
dynamic = ["version", "dependencies"]
description = "Jumpstarter driver for Qualcomm RideSX"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Benny Zlotnik", email = "bzlotnik@redhat.com" }]
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "jumpstarter=={{ version }}",
    "jumpstarter-driver-opendal=={{ version }}",
    "jumpstarter-driver-pyserial=={{ version }}",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_ridesx"]

[tool.uv.sources]
#asyncio_mode = "auto"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest-cov>=6.0.0", "pytest>=8.3.3"]

