// Copyright 2024 The Jumpstarter Authors
// (-- api-linter: core::0215::foreign-type-reference=disabled
// (-- api-linter: core::0192::has-comments=disabled
// (-- api-linter: core::0191::java-package=disabled
// (-- api-linter: core::0191::java-outer-classname=disabled
// (-- api-linter: core::0191::java-multiple-files=disabled

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jumpstarter/client/v1/client.proto

package clientv1

import (
	v1 "github.com/jumpstarter-dev/jumpstarter-controller/internal/protocol/jumpstarter/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exporter struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in jumpstarter/client/v1/client.proto.
	Online        bool              `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Status        v1.ExporterStatus `protobuf:"varint,4,opt,name=status,proto3,enum=jumpstarter.v1.ExporterStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exporter) Reset() {
	*x = Exporter{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exporter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exporter) ProtoMessage() {}

func (x *Exporter) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exporter.ProtoReflect.Descriptor instead.
func (*Exporter) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *Exporter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exporter) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// Deprecated: Marked as deprecated in jumpstarter/client/v1/client.proto.
func (x *Exporter) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Exporter) GetStatus() v1.ExporterStatus {
	if x != nil {
		return x.Status
	}
	return v1.ExporterStatus(0)
}

type Lease struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Selector           string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Duration           *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	EffectiveDuration  *durationpb.Duration   `protobuf:"bytes,4,opt,name=effective_duration,json=effectiveDuration,proto3" json:"effective_duration,omitempty"`
	BeginTime          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=begin_time,json=beginTime,proto3,oneof" json:"begin_time,omitempty"`
	EffectiveBeginTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=effective_begin_time,json=effectiveBeginTime,proto3,oneof" json:"effective_begin_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	EffectiveEndTime   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=effective_end_time,json=effectiveEndTime,proto3,oneof" json:"effective_end_time,omitempty"`
	Client             *string                `protobuf:"bytes,9,opt,name=client,proto3,oneof" json:"client,omitempty"`
	Exporter           *string                `protobuf:"bytes,10,opt,name=exporter,proto3,oneof" json:"exporter,omitempty"`
	Conditions         []*v1.Condition        `protobuf:"bytes,11,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *Lease) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lease) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *Lease) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Lease) GetEffectiveDuration() *durationpb.Duration {
	if x != nil {
		return x.EffectiveDuration
	}
	return nil
}

func (x *Lease) GetBeginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BeginTime
	}
	return nil
}

func (x *Lease) GetEffectiveBeginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveBeginTime
	}
	return nil
}

func (x *Lease) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Lease) GetEffectiveEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveEndTime
	}
	return nil
}

func (x *Lease) GetClient() string {
	if x != nil && x.Client != nil {
		return *x.Client
	}
	return ""
}

func (x *Lease) GetExporter() string {
	if x != nil && x.Exporter != nil {
		return *x.Exporter
	}
	return ""
}

func (x *Lease) GetConditions() []*v1.Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type GetExporterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExporterRequest) Reset() {
	*x = GetExporterRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExporterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExporterRequest) ProtoMessage() {}

func (x *GetExporterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExporterRequest.ProtoReflect.Descriptor instead.
func (*GetExporterRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *GetExporterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListExportersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExportersRequest) Reset() {
	*x = ListExportersRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExportersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportersRequest) ProtoMessage() {}

func (x *ListExportersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportersRequest.ProtoReflect.Descriptor instead.
func (*ListExportersRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *ListExportersRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListExportersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExportersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListExportersRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListExportersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exporters     []*Exporter            `protobuf:"bytes,1,rep,name=exporters,proto3" json:"exporters,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExportersResponse) Reset() {
	*x = ListExportersResponse{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExportersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportersResponse) ProtoMessage() {}

func (x *ListExportersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportersResponse.ProtoReflect.Descriptor instead.
func (*ListExportersResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *ListExportersResponse) GetExporters() []*Exporter {
	if x != nil {
		return x.Exporters
	}
	return nil
}

func (x *ListExportersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaseRequest) Reset() {
	*x = GetLeaseRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaseRequest) ProtoMessage() {}

func (x *GetLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaseRequest.ProtoReflect.Descriptor instead.
func (*GetLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListLeasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	OnlyActive    *bool                  `protobuf:"varint,5,opt,name=only_active,json=onlyActive,proto3,oneof" json:"only_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesRequest) Reset() {
	*x = ListLeasesRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesRequest) ProtoMessage() {}

func (x *ListLeasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesRequest.ProtoReflect.Descriptor instead.
func (*ListLeasesRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{6}
}

func (x *ListLeasesRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListLeasesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLeasesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListLeasesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListLeasesRequest) GetOnlyActive() bool {
	if x != nil && x.OnlyActive != nil {
		return *x.OnlyActive
	}
	return false
}

type ListLeasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leases        []*Lease               `protobuf:"bytes,1,rep,name=leases,proto3" json:"leases,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeasesResponse) Reset() {
	*x = ListLeasesResponse{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeasesResponse) ProtoMessage() {}

func (x *ListLeasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeasesResponse.ProtoReflect.Descriptor instead.
func (*ListLeasesResponse) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{7}
}

func (x *ListLeasesResponse) GetLeases() []*Lease {
	if x != nil {
		return x.Leases
	}
	return nil
}

func (x *ListLeasesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,3,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeaseRequest) Reset() {
	*x = CreateLeaseRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseRequest) ProtoMessage() {}

func (x *CreateLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseRequest.ProtoReflect.Descriptor instead.
func (*CreateLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLeaseRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateLeaseRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *CreateLeaseRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type UpdateLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeaseRequest) Reset() {
	*x = UpdateLeaseRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeaseRequest) ProtoMessage() {}

func (x *UpdateLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeaseRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateLeaseRequest) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *UpdateLeaseRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeaseRequest) Reset() {
	*x = DeleteLeaseRequest{}
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeaseRequest) ProtoMessage() {}

func (x *DeleteLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jumpstarter_client_v1_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeaseRequest) Descriptor() ([]byte, []int) {
	return file_jumpstarter_client_v1_client_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLeaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_jumpstarter_client_v1_client_proto protoreflect.FileDescriptor

const file_jumpstarter_client_v1_client_proto_rawDesc = "" +
	"\n" +
	"\"jumpstarter/client/v1/client.proto\x12\x15jumpstarter.client.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fjumpstarter/v1/kubernetes.proto\x1a\x1bjumpstarter/v1/common.proto\"\xe0\x02\n" +
	"\bExporter\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12C\n" +
	"\x06labels\x18\x02 \x03(\v2+.jumpstarter.client.v1.Exporter.LabelsEntryR\x06labels\x12\x1d\n" +
	"\x06online\x18\x03 \x01(\bB\x05\xe0A\x03\x18\x01R\x06online\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.jumpstarter.v1.ExporterStatusB\x03\xe0A\x03R\x06status\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:_\xeaA\\\n" +
	"\x18jumpstarter.dev/Exporter\x12+namespaces/{namespace}/exporters/{exporter}*\texporters2\bexporter\"\xfa\x06\n" +
	"\x05Lease\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\"\n" +
	"\bselector\x18\x02 \x01(\tB\x06\xe0A\x02\xe0A\x05R\bselector\x12:\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationH\x00R\bduration\x88\x01\x01\x12M\n" +
	"\x12effective_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\x03\xe0A\x03R\x11effectiveDuration\x12>\n" +
	"\n" +
	"begin_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tbeginTime\x88\x01\x01\x12V\n" +
	"\x14effective_begin_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x02R\x12effectiveBeginTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\aendTime\x88\x01\x01\x12R\n" +
	"\x12effective_end_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x04R\x10effectiveEndTime\x88\x01\x01\x12;\n" +
	"\x06client\x18\t \x01(\tB\x1e\xe0A\x03\xfaA\x18\n" +
	"\x16jumpstarter.dev/ClientH\x05R\x06client\x88\x01\x01\x12A\n" +
	"\bexporter\x18\n" +
	" \x01(\tB \xe0A\x03\xfaA\x1a\n" +
	"\x18jumpstarter.dev/ExporterH\x06R\bexporter\x88\x01\x01\x12>\n" +
	"\n" +
	"conditions\x18\v \x03(\v2\x19.jumpstarter.v1.ConditionB\x03\xe0A\x03R\n" +
	"conditions:P\xeaAM\n" +
	"\x15jumpstarter.dev/Lease\x12%namespaces/{namespace}/leases/{lease}*\x06leases2\x05leaseB\v\n" +
	"\t_durationB\r\n" +
	"\v_begin_timeB\x17\n" +
	"\x15_effective_begin_timeB\v\n" +
	"\t_end_timeB\x15\n" +
	"\x13_effective_end_timeB\t\n" +
	"\a_clientB\v\n" +
	"\t_exporter\"J\n" +
	"\x12GetExporterRequest\x124\n" +
	"\x04name\x18\x01 \x01(\tB \xe0A\x02\xfaA\x1a\n" +
	"\x18jumpstarter.dev/ExporterR\x04name\"\xb3\x01\n" +
	"\x14ListExportersRequest\x128\n" +
	"\x06parent\x18\x01 \x01(\tB \xe0A\x02\xfaA\x1a\x12\x18jumpstarter.dev/ExporterR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\"~\n" +
	"\x15ListExportersResponse\x12=\n" +
	"\texporters\x18\x01 \x03(\v2\x1f.jumpstarter.client.v1.ExporterR\texporters\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"D\n" +
	"\x0fGetLeaseRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\n" +
	"\x15jumpstarter.dev/LeaseR\x04name\"\xe8\x01\n" +
	"\x11ListLeasesRequest\x125\n" +
	"\x06parent\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\x12\x15jumpstarter.dev/LeaseR\x06parent\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05B\x03\xe0A\x01R\bpageSize\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\x03\xe0A\x01R\tpageToken\x12\x1b\n" +
	"\x06filter\x18\x04 \x01(\tB\x03\xe0A\x01R\x06filter\x12)\n" +
	"\vonly_active\x18\x05 \x01(\bB\x03\xe0A\x01H\x00R\n" +
	"onlyActive\x88\x01\x01B\x0e\n" +
	"\f_only_active\"r\n" +
	"\x12ListLeasesResponse\x124\n" +
	"\x06leases\x18\x01 \x03(\v2\x1c.jumpstarter.client.v1.LeaseR\x06leases\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa4\x01\n" +
	"\x12CreateLeaseRequest\x125\n" +
	"\x06parent\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\x12\x15jumpstarter.dev/LeaseR\x06parent\x12\x1e\n" +
	"\blease_id\x18\x02 \x01(\tB\x03\xe0A\x01R\aleaseId\x127\n" +
	"\x05lease\x18\x03 \x01(\v2\x1c.jumpstarter.client.v1.LeaseB\x03\xe0A\x02R\x05lease\"\x8f\x01\n" +
	"\x12UpdateLeaseRequest\x127\n" +
	"\x05lease\x18\x01 \x01(\v2\x1c.jumpstarter.client.v1.LeaseB\x03\xe0A\x02R\x05lease\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x01R\n" +
	"updateMask\"G\n" +
	"\x12DeleteLeaseRequest\x121\n" +
	"\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\xfaA\x17\n" +
	"\x15jumpstarter.dev/LeaseR\x04name2\xa7\b\n" +
	"\rClientService\x12\x8d\x01\n" +
	"\vGetExporter\x12).jumpstarter.client.v1.GetExporterRequest\x1a\x1f.jumpstarter.client.v1.Exporter\"2\xdaA\x04name\x82\xd3\xe4\x93\x02%\x12#/v1/{name=namespaces/*/exporters/*}\x12\xa0\x01\n" +
	"\rListExporters\x12+.jumpstarter.client.v1.ListExportersRequest\x1a,.jumpstarter.client.v1.ListExportersResponse\"4\xdaA\x06parent\x82\xd3\xe4\x93\x02%\x12#/v1/{parent=namespaces/*}/exporters\x12\x81\x01\n" +
	"\bGetLease\x12&.jumpstarter.client.v1.GetLeaseRequest\x1a\x1c.jumpstarter.client.v1.Lease\"/\xdaA\x04name\x82\xd3\xe4\x93\x02\"\x12 /v1/{name=namespaces/*/leases/*}\x12\x94\x01\n" +
	"\n" +
	"ListLeases\x12(.jumpstarter.client.v1.ListLeasesRequest\x1a).jumpstarter.client.v1.ListLeasesResponse\"1\xdaA\x06parent\x82\xd3\xe4\x93\x02\"\x12 /v1/{parent=namespaces/*}/leases\x12\x9f\x01\n" +
	"\vCreateLease\x12).jumpstarter.client.v1.CreateLeaseRequest\x1a\x1c.jumpstarter.client.v1.Lease\"G\xdaA\x15parent,lease,lease_id\x82\xd3\xe4\x93\x02):\x05lease\" /v1/{parent=namespaces/*}/leases\x12\xa1\x01\n" +
	"\vUpdateLease\x12).jumpstarter.client.v1.UpdateLeaseRequest\x1a\x1c.jumpstarter.client.v1.Lease\"I\xdaA\x11lease,update_mask\x82\xd3\xe4\x93\x02/:\x05lease2&/v1/{lease.name=namespaces/*/leases/*}\x12\x81\x01\n" +
	"\vDeleteLease\x12).jumpstarter.client.v1.DeleteLeaseRequest\x1a\x16.google.protobuf.Empty\"/\xdaA\x04name\x82\xd3\xe4\x93\x02\"* /v1/{name=namespaces/*/leases/*}B\x82\x02\n" +
	"\x19com.jumpstarter.client.v1B\vClientProtoP\x01Zbgithub.com/jumpstarter-dev/jumpstarter-controller/internal/protocol/jumpstarter/client/v1;clientv1\xa2\x02\x03JCX\xaa\x02\x15Jumpstarter.Client.V1\xca\x02\x15Jumpstarter\\Client\\V1\xe2\x02!Jumpstarter\\Client\\V1\\GPBMetadata\xea\x02\x17Jumpstarter::Client::V1b\x06proto3"

var (
	file_jumpstarter_client_v1_client_proto_rawDescOnce sync.Once
	file_jumpstarter_client_v1_client_proto_rawDescData []byte
)

func file_jumpstarter_client_v1_client_proto_rawDescGZIP() []byte {
	file_jumpstarter_client_v1_client_proto_rawDescOnce.Do(func() {
		file_jumpstarter_client_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jumpstarter_client_v1_client_proto_rawDesc), len(file_jumpstarter_client_v1_client_proto_rawDesc)))
	})
	return file_jumpstarter_client_v1_client_proto_rawDescData
}

var file_jumpstarter_client_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_jumpstarter_client_v1_client_proto_goTypes = []any{
	(*Exporter)(nil),              // 0: jumpstarter.client.v1.Exporter
	(*Lease)(nil),                 // 1: jumpstarter.client.v1.Lease
	(*GetExporterRequest)(nil),    // 2: jumpstarter.client.v1.GetExporterRequest
	(*ListExportersRequest)(nil),  // 3: jumpstarter.client.v1.ListExportersRequest
	(*ListExportersResponse)(nil), // 4: jumpstarter.client.v1.ListExportersResponse
	(*GetLeaseRequest)(nil),       // 5: jumpstarter.client.v1.GetLeaseRequest
	(*ListLeasesRequest)(nil),     // 6: jumpstarter.client.v1.ListLeasesRequest
	(*ListLeasesResponse)(nil),    // 7: jumpstarter.client.v1.ListLeasesResponse
	(*CreateLeaseRequest)(nil),    // 8: jumpstarter.client.v1.CreateLeaseRequest
	(*UpdateLeaseRequest)(nil),    // 9: jumpstarter.client.v1.UpdateLeaseRequest
	(*DeleteLeaseRequest)(nil),    // 10: jumpstarter.client.v1.DeleteLeaseRequest
	nil,                           // 11: jumpstarter.client.v1.Exporter.LabelsEntry
	(v1.ExporterStatus)(0),        // 12: jumpstarter.v1.ExporterStatus
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*v1.Condition)(nil),          // 15: jumpstarter.v1.Condition
	(*fieldmaskpb.FieldMask)(nil), // 16: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_jumpstarter_client_v1_client_proto_depIdxs = []int32{
	11, // 0: jumpstarter.client.v1.Exporter.labels:type_name -> jumpstarter.client.v1.Exporter.LabelsEntry
	12, // 1: jumpstarter.client.v1.Exporter.status:type_name -> jumpstarter.v1.ExporterStatus
	13, // 2: jumpstarter.client.v1.Lease.duration:type_name -> google.protobuf.Duration
	13, // 3: jumpstarter.client.v1.Lease.effective_duration:type_name -> google.protobuf.Duration
	14, // 4: jumpstarter.client.v1.Lease.begin_time:type_name -> google.protobuf.Timestamp
	14, // 5: jumpstarter.client.v1.Lease.effective_begin_time:type_name -> google.protobuf.Timestamp
	14, // 6: jumpstarter.client.v1.Lease.end_time:type_name -> google.protobuf.Timestamp
	14, // 7: jumpstarter.client.v1.Lease.effective_end_time:type_name -> google.protobuf.Timestamp
	15, // 8: jumpstarter.client.v1.Lease.conditions:type_name -> jumpstarter.v1.Condition
	0,  // 9: jumpstarter.client.v1.ListExportersResponse.exporters:type_name -> jumpstarter.client.v1.Exporter
	1,  // 10: jumpstarter.client.v1.ListLeasesResponse.leases:type_name -> jumpstarter.client.v1.Lease
	1,  // 11: jumpstarter.client.v1.CreateLeaseRequest.lease:type_name -> jumpstarter.client.v1.Lease
	1,  // 12: jumpstarter.client.v1.UpdateLeaseRequest.lease:type_name -> jumpstarter.client.v1.Lease
	16, // 13: jumpstarter.client.v1.UpdateLeaseRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 14: jumpstarter.client.v1.ClientService.GetExporter:input_type -> jumpstarter.client.v1.GetExporterRequest
	3,  // 15: jumpstarter.client.v1.ClientService.ListExporters:input_type -> jumpstarter.client.v1.ListExportersRequest
	5,  // 16: jumpstarter.client.v1.ClientService.GetLease:input_type -> jumpstarter.client.v1.GetLeaseRequest
	6,  // 17: jumpstarter.client.v1.ClientService.ListLeases:input_type -> jumpstarter.client.v1.ListLeasesRequest
	8,  // 18: jumpstarter.client.v1.ClientService.CreateLease:input_type -> jumpstarter.client.v1.CreateLeaseRequest
	9,  // 19: jumpstarter.client.v1.ClientService.UpdateLease:input_type -> jumpstarter.client.v1.UpdateLeaseRequest
	10, // 20: jumpstarter.client.v1.ClientService.DeleteLease:input_type -> jumpstarter.client.v1.DeleteLeaseRequest
	0,  // 21: jumpstarter.client.v1.ClientService.GetExporter:output_type -> jumpstarter.client.v1.Exporter
	4,  // 22: jumpstarter.client.v1.ClientService.ListExporters:output_type -> jumpstarter.client.v1.ListExportersResponse
	1,  // 23: jumpstarter.client.v1.ClientService.GetLease:output_type -> jumpstarter.client.v1.Lease
	7,  // 24: jumpstarter.client.v1.ClientService.ListLeases:output_type -> jumpstarter.client.v1.ListLeasesResponse
	1,  // 25: jumpstarter.client.v1.ClientService.CreateLease:output_type -> jumpstarter.client.v1.Lease
	1,  // 26: jumpstarter.client.v1.ClientService.UpdateLease:output_type -> jumpstarter.client.v1.Lease
	17, // 27: jumpstarter.client.v1.ClientService.DeleteLease:output_type -> google.protobuf.Empty
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_jumpstarter_client_v1_client_proto_init() }
func file_jumpstarter_client_v1_client_proto_init() {
	if File_jumpstarter_client_v1_client_proto != nil {
		return
	}
	file_jumpstarter_client_v1_client_proto_msgTypes[1].OneofWrappers = []any{}
	file_jumpstarter_client_v1_client_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jumpstarter_client_v1_client_proto_rawDesc), len(file_jumpstarter_client_v1_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jumpstarter_client_v1_client_proto_goTypes,
		DependencyIndexes: file_jumpstarter_client_v1_client_proto_depIdxs,
		MessageInfos:      file_jumpstarter_client_v1_client_proto_msgTypes,
	}.Build()
	File_jumpstarter_client_v1_client_proto = out.File
	file_jumpstarter_client_v1_client_proto_goTypes = nil
	file_jumpstarter_client_v1_client_proto_depIdxs = nil
}
