//! The typestate carrier and the `Fsm` trait.
//!
//! A machine is a set of zero-sized (or data-carrying) state structs plus a hand-written
//! wrapper enum. `Handle<Ctx, S>` carries an application context `Ctx` together with the
//! current type-level state `S`. Transitions are hand-written methods on `Handle<Ctx, S>`
//! that consume `self` and return the *concrete* successor `Handle<Ctx, T>` — so the
//! transition graph is encoded in the type signatures and an illegal transition simply does
//! not type-check. Type-erasure to the wrapper enum happens only at the mailbox/runner seam,
//! via the `From<Handle<Ctx, S>>` impls that `#[derive(StateMachine)]` generates.

use tokio_stream::{Stream, StreamExt};

/// Marker for non-terminal (live) states. `#[derive(StateMachine)]` implements it for every
/// non-`#[terminal]` variant's state, which lets a consumer gate cross-cutting transitions
/// (e.g. `fail`) behind `impl<S: Live> ...` so a terminal state can't be failed.
pub trait Live {}

/// Compile-time typestate handle: the carried context plus the current typed state. Each
/// machine picks its own `Ctx` (e.g. `Lease<S> = Handle<LeaseContext, S>`), which also keeps
/// distinct machines distinct types so their per-machine impls don't collide.
#[derive(Clone)]
pub struct Handle<Ctx, S> {
    ctx: Ctx,
    state: S,
}

impl<Ctx, S> Handle<Ctx, S> {
    /// Construct a handle from a context and an initial state. State structs are expected to
    /// keep their fields module-private (sealed construction), so in practice only the
    /// machine's own module can build the non-initial states this carries.
    pub fn new(ctx: Ctx, state: S) -> Self {
        Handle { ctx, state }
    }

    /// Transition into the next typed state, carrying the context forward, and return the
    /// *concrete* next handle. A hand-written transition is then just
    /// `self.into_state(Next).into()` (the `.into()` erases to the wrapper at the seam).
    pub fn into_state<T>(self, next: T) -> Handle<Ctx, T> {
        Handle {
            ctx: self.ctx,
            state: next,
        }
    }

    /// The carried context — read it in any transition that needs machine-global state.
    pub fn ctx(&self) -> &Ctx {
        &self.ctx
    }

    /// Mutable access to the carried context (e.g. to record a stable identity mid-flight).
    pub fn ctx_mut(&mut self) -> &mut Ctx {
        &mut self.ctx
    }

    /// The current state's data.
    pub fn state(&self) -> &S {
        &self.state
    }

    /// Mutable access to the current state's data.
    pub fn state_mut(&mut self) -> &mut S {
        &mut self.state
    }

    /// Decompose into context and state.
    pub fn into_parts(self) -> (Ctx, S) {
        (self.ctx, self.state)
    }
}

/// The runtime face of a typestate machine. The wrapper enum implements this (generated by
/// `#[derive(StateMachine)]`), which gives every machine the same signal-driven surface and
/// the [`Fsm::drive`] async iterator for free.
pub trait Fsm: Sized {
    /// The machine's signal type (an enum of *facts*, never transition commands).
    type Signal;

    /// Route a signal to the current state. Live states dispatch to their hand-written
    /// `apply`; terminal states ignore every signal.
    fn apply(self, signal: Self::Signal) -> Self;

    /// Whether this is a terminal state — drives stream completion in `drive`.
    fn is_terminal(&self) -> bool;

    /// Drive the machine from an async stream of signals, yielding each resulting state as an
    /// async iterator: the initial state first, then one item per signal, completing after the
    /// first terminal state. Kept for pure, stream-style observation/tests; the production
    /// exporter uses a typed per-state `enter` loop instead (so it can run effects and observe
    /// per-signal outcomes), but both share `apply`.
    fn drive(
        self,
        signals: impl Stream<Item = Self::Signal> + Send,
    ) -> impl Stream<Item = Self> + Send
    where
        Self: Clone + Send + 'static,
        Self::Signal: Send,
    {
        async_stream::stream! {
            tokio::pin!(signals);
            let mut state = self;
            yield state.clone();
            while !state.is_terminal() {
                let Some(signal) = signals.next().await else { break };
                state = state.apply(signal);
                yield state.clone();
            }
        }
    }
}
