FROM --platform=$BUILDPLATFORM ghcr.io/astral-sh/uv:0.11.28@sha256:0f36cb9361a3346885ca3677e3767016687b5a170c1a6b88465ec14aefec90aa AS uv-bin
FROM --platform=$BUILDPLATFORM registry.fedoraproject.org/fedora:44 AS builder
COPY --from=uv-bin /uv /uvx /bin/
RUN dnf install -y make git && \
    dnf clean all && \
    rm -rf /var/cache/dnf
COPY .py-version /tmp/.py-version
RUN uv python install "$(cat /tmp/.py-version)"
ENV UV_PYTHON_PREFERENCE=only-managed
ADD . /src
RUN make -C /src/python build


FROM quay.io/devfile/base-developer-image:ubi10-latest AS python-base
LABEL maintainer="jumpstarter.dev"

LABEL name="devfile/udi10/jumpstarter-client"

LABEL summary="devfile jumpstarter developer image"
LABEL description="Devspaces image for consuming jumpstarter as a client"
LABEL io.k8s.display-name="jumpstarter-client-developer"

COPY --from=ghcr.io/astral-sh/uv:0.11.28@sha256:0f36cb9361a3346885ca3677e3767016687b5a170c1a6b88465ec14aefec90aa /uv /uvx /bin/

USER root
COPY .py-version /tmp/.py-version
RUN dnf -y install make git libusbx golang && dnf clean all

USER 10001
RUN uv python install "$(cat /tmp/.py-version)"

FROM python-base
RUN --mount=from=builder,source=/src/python/dist,target=/dist \
    uv venv /home/user/.venv && \
    VIRTUAL_ENV=/home/user/.venv uv pip install /dist/*.whl pyusb pytest
ENV PATH="/home/user/.venv/bin:$PATH"

USER root
RUN mkdir -p /home/user/.config/jumpstarter/clients
RUN chown 10001:0 -R /home/user/{.config,.local,.cache,.venv} && chmod g+rwx -R /home/user/{.config,.local,.cache,.venv}

USER 10001
