FROM quay.io/devfile/base-developer-image:ubi10-latest@sha256:6b9d2a3b90798e6d92c1c6b05cd2ce733b989cc6f0b3ff4e0820b45ad19fe474
LABEL maintainer="Jumpstarter.dev"

LABEL name="devfile/udi9/jumpstarter"

#labels for container catalog
LABEL summary="devfile jumpstarter developer image"
LABEL description="Image with developers tools."
LABEL io.k8s.display-name="jumpstarter-developer-universal"

USER root

COPY --from=ghcr.io/astral-sh/uv:0.11.19 /uv /uvx /bin/

COPY .py-version /tmp/.py-version
RUN grep -qxE '[0-9]+\.[0-9]+' /tmp/.py-version && \
    PY=$(cat /tmp/.py-version) && \
    dnf -y install make git "python${PY}" libusbx python3-pyusb golang podman && dnf clean all

USER 10001

RUN echo "alias python='uv run python'" >> /home/user/.bashrc
