FROM quay.io/devfile/base-developer-image:ubi10-latest
LABEL maintainer="Jumpstarter.dev"

LABEL name="devfile/udi10/jumpstarter"

LABEL summary="devfile jumpstarter developer image"
LABEL description="Image with developers tools."
LABEL io.k8s.display-name="jumpstarter-developer-universal"

COPY --from=ghcr.io/astral-sh/uv:0.11.23@sha256:d0a0a753ab981624b49c97abc98821c1c09f4ca69d1ef5cee69c501be3d88479 /uv /uvx /bin/

USER root
COPY .py-version /tmp/.py-version
RUN dnf -y install make git libusbx golang podman && dnf clean all

USER 10001
ENV UV_PYTHON_PREFERENCE=only-managed
RUN uv python install "$(cat /tmp/.py-version)" && \
    uv venv /home/user/.venv
ENV PATH="/home/user/.venv/bin:${PATH}"

USER root
RUN chown 10001:0 -R /home/user/{.local,.cache,.venv} && chmod g+rwx -R /home/user/{.local,.cache,.venv}

USER 10001
