FROM quay.io/devfile/base-developer-image:ubi9-latest
LABEL maintainer="Jumpstarter.dev"

LABEL name="devfile/udi9/jumpstarter"

#labels for container catalog
LABEL summary="devfile jumpstarter developer image"
LABEL description="Image with developers tools."
LABEL io.k8s.display-name="jumpstarter-developer-universal"

USER root

COPY .uv-version /tmp/.uv-version
RUN curl -LsSf "https://astral.sh/uv/$(cat /tmp/.uv-version)/install.sh" | sh && \
    mv /root/.local/bin/uv /bin/uv && mv /root/.local/bin/uvx /bin/uvx

COPY .py-version /tmp/.py-version
RUN PY=$(cat /tmp/.py-version) && \
    dnf -y install make git "python${PY}" libusbx python3-pyusb golang podman && dnf clean all

USER 10001

RUN echo "alias python='uv run python'" >> /home/user/.bashrc
