apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  namespace: {{ .Release.Namespace }}
  name: dev-jumpstarter-adb-v1
spec:
  proto:
    package: jumpstarter.interfaces.adb.v1
    descriptor: CglhZGIucHJvdG8SHWp1bXBzdGFydGVyLmludGVyZmFjZXMuYWRiLnYxGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8iIwoSS2lsbFNlcnZlclJlc3BvbnNlEg0KBXZhbHVlGAEgASgDIiQKE0xpc3REZXZpY2VzUmVzcG9uc2USDQoFdmFsdWUYASABKAkiJAoTU3RhcnRTZXJ2ZXJSZXNwb25zZRINCgV2YWx1ZRgBIAEoAzKmAgoJQWRiU2VydmVyElsKCktpbGxTZXJ2ZXISFi5nb29nbGUucHJvdG9idWYuRW1wdHkaMS5qdW1wc3RhcnRlci5pbnRlcmZhY2VzLmFkYi52MS5LaWxsU2VydmVyUmVzcG9uc2UoADAAEl0KC0xpc3REZXZpY2VzEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjIuanVtcHN0YXJ0ZXIuaW50ZXJmYWNlcy5hZGIudjEuTGlzdERldmljZXNSZXNwb25zZSgAMAASXQoLU3RhcnRTZXJ2ZXISFi5nb29nbGUucHJvdG9idWYuRW1wdHkaMi5qdW1wc3RhcnRlci5pbnRlcmZhY2VzLmFkYi52MS5TdGFydFNlcnZlclJlc3BvbnNlKAAwAErNAwr8AQoCBgAa9QFBREIgc2VydmVyIGRyaXZlciB0aGF0IHR1bm5lbHMgQURCIGNvbm5lY3Rpb25zIG92ZXIgSnVtcHN0YXJ0ZXIuCgpNYW5hZ2VzIGFuIEFEQiBkYWVtb24gb24gdGhlIGV4cG9ydGVyIGFuZCBleHBvc2VzIGl0IHZpYSBUQ1AgdHVubmVsLgpDbGllbnQtc2lkZSB0b29scyAoYWRiLCBBbmRyb2lkIFN0dWRpbywgdHJhZGVmZWQpIGNvbm5lY3QgdGhyb3VnaAp0aGUgdHVubmVsIGFzIGlmIHRoZSBBREIgc2VydmVyIHdlcmUgbG9jYWwuCgpGCgQGAAIAGj5LaWxsIHRoZSBBREIgc2VydmVyIG9uIHRoZSBleHBvcnRlci4gUmV0dXJucyB0aGUgcG9ydCBudW1iZXIuCgo7CgQGAAIBGjNMaXN0IGRldmljZXMgdmlzaWJsZSB0byB0aGUgZXhwb3J0ZXIncyBBREIgc2VydmVyLgoKRwoEBgACAho/U3RhcnQgdGhlIEFEQiBzZXJ2ZXIgb24gdGhlIGV4cG9ydGVyLiBSZXR1cm5zIHRoZSBwb3J0IG51bWJlci4KYgZwcm90bzM=
  drivers:
    - language: python
      package: jumpstarter-driver-adb
      clientClass: "jumpstarter_driver_adb.client.AdbClient"
