apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  namespace: {{ .Release.Namespace }}
  name: dev-jumpstarter-storage-mux-flasher-v1
spec:
  proto:
    package: jumpstarter.interfaces.storage_mux_flasher.v1
    descriptor: ChlzdG9yYWdlX211eF9mbGFzaGVyLnByb3RvEi1qdW1wc3RhcnRlci5pbnRlcmZhY2VzLnN0b3JhZ2VfbXV4X2ZsYXNoZXIudjEaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90byIaCgtSZWFkUmVxdWVzdBILCgNkc3QYASABKAkiGwoMV3JpdGVSZXF1ZXN0EgsKA3NyYxgBIAEoCTKQAwoaU3RvcmFnZU11eEZsYXNoZXJJbnRlcmZhY2USOQoDRHV0EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5KAAwABI6CgRIb3N0EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5KAAwABI5CgNPZmYSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkoADAAEl4KBFJlYWQSOi5qdW1wc3RhcnRlci5pbnRlcmZhY2VzLnN0b3JhZ2VfbXV4X2ZsYXNoZXIudjEuUmVhZFJlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkoADAAEmAKBVdyaXRlEjsuanVtcHN0YXJ0ZXIuaW50ZXJmYWNlcy5zdG9yYWdlX211eF9mbGFzaGVyLnYxLldyaXRlUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgAMABK9AIKOQoCBgAaM1N0b3JhZ2UgbXV4IHdpdGggaW50ZWdyYXRlZCBmbGFzaGluZyBjYXBhYmlsaXRpZXMuCgo9CgQGAAIAGjVDb25uZWN0IHRoZSBzdG9yYWdlIGRldmljZSB0byB0aGUgZGV2aWNlIHVuZGVyIHRlc3QuCgowCgQGAAIBGihDb25uZWN0IHRoZSBzdG9yYWdlIGRldmljZSB0byB0aGUgaG9zdC4KCj4KBAYAAgIaNkRpc2Nvbm5lY3QgdGhlIHN0b3JhZ2UgZGV2aWNlIGZyb20gYm90aCBob3N0IGFuZCBEVVQuCgo/CgQGAAIDGjdSZWFkIHRoZSBzdG9yYWdlIGRldmljZSBjb250ZW50cyB0byBhIHJlc291cmNlIGhhbmRsZS4KCkUKBAYAAgQaPVdyaXRlIGFuIGltYWdlIGZyb20gYSByZXNvdXJjZSBoYW5kbGUgdG8gdGhlIHN0b3JhZ2UgZGV2aWNlLgpiBnByb3RvMw==
  drivers:
    - language: python
      package: jumpstarter-driver-opendal
      clientClass: "jumpstarter_driver_opendal.client.StorageMuxFlasherClient"
      driverClasses:
        - "jumpstarter_driver_opendal.driver:MockStorageMuxFlasher"
