[project]
name = "jumpstarter-cli-common"
dynamic = ["version", "dependencies"]
description = ""
authors = [{ name = "Kirk Brauer", email = "kbrauer@hatci.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
  "jumpstarter=={{ version }}",
  "pydantic>=2.8.2",
  "click>=8.1.7.2",
  "authlib>=1.4.1",
  "truststore>=0.10.1",
  "joserfc>=1.0.3",
  "yarl>=1.18.3",
  "rich>=14.0.0",
]

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-anyio>=0.0.0",
  "pytest-asyncio>=0.0.0",
  "pytest-cov>=5.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["jumpstarter_cli_common"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

