apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: uboot
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  uboot:
    type: jumpstarter_driver_uboot.driver.UbootConsole
    children:
      power:
        type: jumpstarter_driver_power.driver.MockPower
        config: {}
      serial:
        type: jumpstarter_driver_pyserial.driver.PySerial
        config:
          url: loop://
    config:
      prompt: =>
