# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import adb_pb2 as adb__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdbServerStub(object):
    """ADB server driver that tunnels ADB connections over Jumpstarter.

    Manages an ADB daemon on the exporter and exposes it via TCP tunnel.
    Client-side tools (adb, Android Studio, tradefed) connect through
    the tunnel as if the ADB server were local.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.KillServer = channel.unary_unary(
                '/jumpstarter.interfaces.adb.v1.AdbServer/KillServer',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adb__pb2.KillServerResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/jumpstarter.interfaces.adb.v1.AdbServer/ListDevices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adb__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.StartServer = channel.unary_unary(
                '/jumpstarter.interfaces.adb.v1.AdbServer/StartServer',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adb__pb2.StartServerResponse.FromString,
                _registered_method=True)


class AdbServerServicer(object):
    """ADB server driver that tunnels ADB connections over Jumpstarter.

    Manages an ADB daemon on the exporter and exposes it via TCP tunnel.
    Client-side tools (adb, Android Studio, tradefed) connect through
    the tunnel as if the ADB server were local.
    """

    def KillServer(self, request, context):
        """Kill the ADB server on the exporter. Returns the port number.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """List devices visible to the exporter's ADB server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartServer(self, request, context):
        """Start the ADB server on the exporter. Returns the port number.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdbServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'KillServer': grpc.unary_unary_rpc_method_handler(
                    servicer.KillServer,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adb__pb2.KillServerResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adb__pb2.ListDevicesResponse.SerializeToString,
            ),
            'StartServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartServer,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adb__pb2.StartServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jumpstarter.interfaces.adb.v1.AdbServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jumpstarter.interfaces.adb.v1.AdbServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdbServer(object):
    """ADB server driver that tunnels ADB connections over Jumpstarter.

    Manages an ADB daemon on the exporter and exposes it via TCP tunnel.
    Client-side tools (adb, Android Studio, tradefed) connect through
    the tunnel as if the ADB server were local.
    """

    @staticmethod
    def KillServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.adb.v1.AdbServer/KillServer',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adb__pb2.KillServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.adb.v1.AdbServer/ListDevices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adb__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.adb.v1.AdbServer/StartServer',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adb__pb2.StartServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
