import { defineConfig } from "vitest/config";

// E2E suite for the TypeScript SDK. Hits the controller's HTTPS admin
// API on port 8082 with a real Dex-issued bearer token. Fixtures
// (Dex users, RBAC, Webhook CRD, the in-cluster echo pod) are created
// by the Go e2e harness via `bash e2e/setup-e2e.sh`; running this
// suite assumes that has already happened.
export default defineConfig({
  test: {
    include: ["test/e2e/**/*.test.ts"],
    testTimeout: 120_000,
    hookTimeout: 120_000,
    // Tests share fixtures (the in-cluster echo pod, the developer
    // namespace bindings) so run sequentially to keep fixture
    // mutations deterministic. The whole suite finishes in well
    // under a minute against a warm cluster.
    fileParallelism: false,
    sequence: {
      concurrent: false,
    },
    // The controller serves on 8082 with a self-signed cert and Dex
    // is signed by the CA generated by setup-e2e.sh. Disable TLS
    // verification globally — the bearer-token validation is the
    // real security boundary, same as the Go e2e suite does with
    // InsecureSkipVerify.
    setupFiles: ["test/e2e/setup.ts"],
  },
});
