[project]
name = "jumpstarter-cli"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
  "jumpstarter-cli-admin=={{ version }}",
  "jumpstarter-cli-driver=={{ version }}",
]

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-anyio>=0.0.0",
  "pytest-asyncio>=0.0.0",
  "pytest-cov>=5.0.0",
]

[project.scripts]
jmp = "jumpstarter_cli.jmp:jmp"
j = "jumpstarter_cli.j:j"

[tool.hatch.build.targets.wheel]
packages = ["jumpstarter_cli"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

