[project]
name = "jumpstarter-driver-opendal"
dynamic = [
    "version",
    "urls",
]
description = ""
authors = [
    { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
    { name = "Nick Cao", email = "ncao@redhat.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
    "jumpstarter ~= 0.6",
    "opendal>=0.45.8",
    "asyncclick>=8.1.7.2",
]

[project.entry-points."jumpstarter.adapters"]
Opendal = "jumpstarter_driver_opendal.adapters:OpendalAdapter"

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"
