[project]
name = "jumpstarter-driver-energenie"
dynamic = ["version", "dependencies"]
description = "Energenie is an advanced surge protector with power management features"
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [
    { name = "Enric Balletbo i Serra", email = "eballetbo@redhat.com" }
]
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter=={{ version }}",
    "jumpstarter-driver-power=={{ version }}"
]

[project.entry-points."jumpstarter.drivers"]
EnerGenie = "jumpstarter_driver_energenie.driver:EnerGenie"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pytest-httpserver>=1.0.0",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"
