//! Integration tests against ConfigMap fixtures generated by the *Go* writer.
//!
//! The YAML files under `tests/fixtures/` were produced by marshaling
//! representative `config.Config` / `config.Router` values with
//! sigs.k8s.io/yaml — exactly what the operator's `createConfigMap`
//! (`buildConfig` / `buildRouter` in
//! `controller/deploy/operator/internal/controller/jumpstarter/jumpstarter_controller.go`)
//! writes into the `jumpstarter-controller` ConfigMap:
//!
//! - `config.yaml`         — the e2e kind deployment (e2e/values.kind.yaml):
//!   internal auth defaults + the dex JWT authenticator.
//! - `config_full.yaml`    — every field the Go types contain populated.
//! - `config_minimal.yaml` — everything disabled/absent (zero values).
//! - `router.yaml`         — buildRouter output for 3 replicas.
//!
//! Each fixture must (a) parse into the typed model, (b) survive a
//! serialize→parse round trip unchanged, and (c) re-serialize to a YAML
//! document *value-identical* to the Go-written original (proving the Rust
//! writer emits the same wire shape the Go reader/writer pair uses).

use jumpstarter_controller_config::router::Router;
use jumpstarter_controller_config::types::Config;
use serde::{de::DeserializeOwned, Serialize};

fn fixture(name: &str) -> String {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read_to_string(&path).unwrap_or_else(|err| panic!("read {path}: {err}"))
}

/// Parses the fixture, round-trips it, and checks value-level equality of the
/// re-serialized YAML against the Go-generated original.
fn assert_faithful<T>(name: &str) -> T
where
    T: DeserializeOwned + Serialize + PartialEq + std::fmt::Debug,
{
    let original = fixture(name);
    let parsed: T =
        serde_yaml_ng::from_str(&original).unwrap_or_else(|err| panic!("parse {name}: {err}"));

    let reserialized =
        serde_yaml_ng::to_string(&parsed).unwrap_or_else(|err| panic!("serialize {name}: {err}"));
    let reparsed: T = serde_yaml_ng::from_str(&reserialized)
        .unwrap_or_else(|err| panic!("re-parse {name}: {err}"));
    assert_eq!(reparsed, parsed, "{name}: round trip must be lossless");

    // Compare as untyped YAML values: same keys, same values — key order and
    // string quoting style may differ from Go, but the document must not.
    let original_value: serde_yaml_ng::Value = serde_yaml_ng::from_str(&original).unwrap();
    let reserialized_value: serde_yaml_ng::Value = serde_yaml_ng::from_str(&reserialized).unwrap();
    assert_eq!(
        reserialized_value, original_value,
        "{name}: re-serialized YAML diverges from the Go-written document.\n\
         Go wrote:\n{original}\nRust wrote:\n{reserialized}"
    );

    parsed
}

#[test]
fn e2e_config_fixture() {
    let cfg: Config = assert_faithful("config.yaml");

    // Values pinned to the operator's buildConfig output for the e2e values.
    assert_eq!(cfg.authentication.internal.prefix, "internal:");
    assert_eq!(cfg.authentication.internal.token_lifetime, "43800h0m0s");
    assert!(!cfg.authentication.k8s.enabled);
    assert!(cfg.provisioning.enabled);
    assert_eq!(cfg.grpc.keepalive.min_time, "1s");
    assert!(cfg.grpc.keepalive.permit_without_stream);
    assert_eq!(cfg.grpc.keepalive.timeout, "");
    assert_eq!(cfg.lease_policy.max_tags, 10);

    assert_eq!(cfg.authentication.jwt.len(), 1);
    let dex = &cfg.authentication.jwt[0];
    assert_eq!(dex.issuer.url, "https://dex.dex.svc.cluster.local:5556");
    assert_eq!(dex.issuer.audiences, vec!["jumpstarter-cli"]);
    assert_eq!(dex.issuer.audience_match_policy, "MatchAny");
    assert!(dex
        .issuer
        .certificate_authority
        .starts_with("-----BEGIN CERTIFICATE-----\n"));
    assert_eq!(dex.claim_mappings.username.claim, "name");
    assert_eq!(dex.claim_mappings.username.prefix.as_deref(), Some("dex:"));
    // Go marshals the zero groups/uid mappings as `{}`.
    assert_eq!(dex.claim_mappings.groups, Default::default());
    assert_eq!(dex.claim_mappings.uid, Default::default());

    // The token lifetime written by the operator parses as a Go duration.
    assert_eq!(
        jumpstarter_controller_config::duration::parse_config_duration(
            &cfg.authentication.internal.token_lifetime
        ),
        Ok(43800 * jumpstarter_controller_config::duration::HOUR)
    );
}

#[test]
fn full_config_fixture() {
    let cfg: Config = assert_faithful("config_full.yaml");

    assert!(cfg.authentication.k8s.enabled);
    assert!(!cfg.provisioning.enabled);
    assert_eq!(cfg.authentication.internal.token_lifetime, "720h");

    // Full keepalive surface.
    let ka = &cfg.grpc.keepalive;
    assert_eq!(
        (
            ka.min_time.as_str(),
            ka.permit_without_stream,
            ka.timeout.as_str(),
            ka.interval_time.as_str(),
            ka.max_connection_idle.as_str(),
            ka.max_connection_age.as_str(),
            ka.max_connection_age_grace.as_str(),
        ),
        ("1s", true, "180s", "10s", "5m", "30m", "10s")
    );

    let jwt = &cfg.authentication.jwt[0];
    assert_eq!(
        jwt.issuer.discovery_url.as_deref(),
        Some("https://oidc.oidc-namespace/.well-known/openid-configuration")
    );
    assert_eq!(jwt.issuer.audiences, vec!["foo", "bar"]);
    assert_eq!(jwt.claim_validation_rules.len(), 2);
    assert_eq!(jwt.claim_validation_rules[0].claim, "hd");
    assert_eq!(jwt.claim_validation_rules[0].required_value, "example.com");
    assert_eq!(
        jwt.claim_validation_rules[1].expression,
        "claims.exp - claims.nbf <= 86400"
    );
    assert_eq!(jwt.claim_mappings.username.prefix.as_deref(), Some("oidc:"));
    // groups.prefix is *string in Go: explicitly set to "" here — must be
    // Some(""), not None.
    assert_eq!(jwt.claim_mappings.groups.claim, "groups");
    assert_eq!(jwt.claim_mappings.groups.prefix.as_deref(), Some(""));
    assert_eq!(jwt.claim_mappings.uid.claim, "uid");
    assert_eq!(jwt.claim_mappings.extra.len(), 1);
    assert_eq!(jwt.claim_mappings.extra[0].key, "example.com/tenant");
    assert_eq!(
        jwt.claim_mappings.extra[0].value_expression,
        "claims.tenant"
    );
    assert_eq!(jwt.user_validation_rules.len(), 1);
    assert_eq!(
        jwt.user_validation_rules[0].expression,
        "!user.username.startsWith('system:')"
    );

    // Every keepalive duration in the fixture parses under Go semantics.
    for value in [
        &ka.min_time,
        &ka.timeout,
        &ka.interval_time,
        &ka.max_connection_idle,
        &ka.max_connection_age,
        &ka.max_connection_age_grace,
    ] {
        jumpstarter_controller_config::duration::parse_config_duration(value)
            .unwrap_or_else(|err| panic!("keepalive duration {value:?}: {err}"));
    }
}

#[test]
fn minimal_config_fixture() {
    let cfg: Config = assert_faithful("config_minimal.yaml");

    assert_eq!(cfg.authentication.internal.prefix, "");
    assert_eq!(cfg.authentication.internal.token_lifetime, "");
    assert!(cfg.authentication.jwt.is_empty());
    assert!(!cfg.authentication.k8s.enabled);
    assert!(!cfg.provisioning.enabled);
    assert_eq!(cfg.lease_policy.max_tags, 0);
    assert_eq!(cfg.grpc.keepalive.min_time, "1s");
}

#[test]
fn router_fixture() {
    let router: Router = assert_faithful("router.yaml");

    assert_eq!(router.len(), 3);
    assert_eq!(
        router["default"].endpoint,
        "router-0.jumpstarter.127.0.0.1.nip.io:443"
    );
    // buildRouter: the first replica ("default") carries no labels.
    assert!(router["default"].labels.is_empty());
    for i in [1, 2] {
        let entry = &router[&format!("router-{i}")];
        assert_eq!(
            entry.endpoint,
            format!("router-{i}.jumpstarter.127.0.0.1.nip.io:443")
        );
        assert_eq!(entry.labels["router-index"], i.to_string());
        assert_eq!(entry.labels.len(), 1);
    }
}
