[project]
name = "jumpstarter_driver_corellium"
dynamic = ["version", "dependencies"]
description = ""
authors = [{ name = "Leonardo Rossetti", email = "lrossett@redhat.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
  "jumpstarter=={{ version }}",
  "jumpstarter-driver-composite=={{ version }}",
  "jumpstarter-driver-power=={{ version }}",
  "jumpstarter-driver-network=={{ version }}",
  "jumpstarter-driver-pyserial=={{ version }}",
  "click>=8.1.7.2",
]

[project.entry-points."jumpstarter.drivers"]
Corellium = "jumpstarter_driver_corellium.driver:Corellium"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "trio>=0.28.0", "requests_mock", "pytest-asyncio>=0.25.3"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

