apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: noyito-relay
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  relay1:
    type: jumpstarter_driver_noyito_relay.driver.NoyitoPowerSerial
    config:
      port: /dev/ttyUSB0
      channel: 1
  relay2:
    type: jumpstarter_driver_noyito_relay.driver.NoyitoPowerSerial
    config:
      port: /dev/ttyUSB0
      channel: 2
