[project]
name = "jumpstarter-driver-pyserial"
dynamic = ["version", "urls"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = [
  "jumpstarter",
  "jumpstarter-driver-network",
  "pyserial>=3.5",
  "asyncclick>=8.1.7.2",
]

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-cov>=5.0.0",
  "types-pexpect>=4.9.0.20241208",
  "types-pyserial>=3.5.0.20250130",
]

[project.entry-points."jumpstarter.drivers"]
PySerial = "jumpstarter_driver_pyserial.driver:PySerial"

[project.entry-points."jumpstarter.clients"]
PySerialClient = "jumpstarter_driver_pyserial.client:PySerialClient"

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
