---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jumpstarter-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients
  - exporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients/finalizers
  - exporters/finalizers
  verbs:
  - update
- apiGroups:
  - jumpstarter.dev
  resources:
  - clients/status
  - exporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - jumpstarter.dev
  resources:
  - exporteraccesspolicies
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - exportersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - exportersets/finalizers
  verbs:
  - update
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - exportersets/scale
  - exportersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - virtualtarget.jumpstarter.dev
  resources:
  - virtualtargetclasses
  verbs:
  - get
  - list
  - watch
