apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  name: dev-jumpstarter-network-v1
spec:
  proto:
    package: jumpstarter.interfaces.network.v1
    descriptor: Cg1uZXR3b3JrLnByb3RvEiFqdW1wc3RhcnRlci5pbnRlcmZhY2VzLm5ldHdvcmsudjEaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bzJRChBOZXR3b3JrSW50ZXJmYWNlEj0KB0Nvbm5lY3QSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkoATABSogBCkIKAgYAGjxCaWRpcmVjdGlvbmFsIGJ5dGUgc3RyZWFtIGNvbm5lY3Rpb24gdG8gYSBuZXR3b3JrIGVuZHBvaW50LgoKQgoEBgACABo6T3BlbiBhIGJpZGlyZWN0aW9uYWwgYnl0ZSBzdHJlYW0gdG8gdGhlIG5ldHdvcmsgZW5kcG9pbnQuCmIGcHJvdG8z
  drivers:
    - language: python
      package: jumpstarter-driver-network
      clientClass: "jumpstarter_driver_network.client.NetworkClient"
      driverClasses:
        - "jumpstarter_driver_network.driver:DbusNetwork"
        - "jumpstarter_driver_network.driver:EchoNetwork"
        - "jumpstarter_driver_network.driver:TcpNetwork"
        - "jumpstarter_driver_network.driver:UdpNetwork"
        - "jumpstarter_driver_network.driver:UnixNetwork"
        - "jumpstarter_driver_network.driver:VsockNetwork"
        - "jumpstarter_driver_network.driver:WebsocketNetwork"
    - language: java
      package: ":java:jumpstarter-driver-network"
      clientClass: "dev.jumpstarter.driver.network.NetworkClient"
    - language: typescript
      package: "@jumpstarter/driver-network"
      clientClass: "NetworkClient"
    - language: rust
      package: "jumpstarter-driver-network"
      clientClass: "jumpstarter_driver_network::NetworkClient"
