apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  name: dev-jumpstarter-virtual-power-v1
spec:
  proto:
    package: jumpstarter.interfaces.virtual_power.v1
    descriptor: ChN2aXJ0dWFsX3Bvd2VyLnByb3RvEidqdW1wc3RhcnRlci5pbnRlcmZhY2VzLnZpcnR1YWxfcG93ZXIudjEaG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90byIdCgpPZmZSZXF1ZXN0Eg8KB2Rlc3Ryb3kYASABKAgiMAoMUG93ZXJSZWFkaW5nEg8KB3ZvbHRhZ2UYASABKAESDwoHY3VycmVudBgCIAEoATKEAgoVVmlydHVhbFBvd2VySW50ZXJmYWNlElYKA09mZhIzLmp1bXBzdGFydGVyLmludGVyZmFjZXMudmlydHVhbF9wb3dlci52MS5PZmZSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5KAAwABI4CgJPbhIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSgAMAASWQoEUmVhZBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRo1Lmp1bXBzdGFydGVyLmludGVyZmFjZXMudmlydHVhbF9wb3dlci52MS5Qb3dlclJlYWRpbmcoADABStkCCkUKAgYAGj9Db250cm9sIGEgdmlydHVhbCBwb3dlciBzb3VyY2Ugd2l0aCBvcHRpb25hbCByZXNvdXJjZSBjbGVhbnVwLgoKWQoEBgACABpRRGVhY3RpdmF0ZSB0aGUgdmlydHVhbCBwb3dlciBzb3VyY2UsIG9wdGlvbmFsbHkgZGVzdHJveWluZyBhc3NvY2lhdGVkIHJlc291cmNlcy4KCisKBAYAAgEaI0FjdGl2YXRlIHRoZSB2aXJ0dWFsIHBvd2VyIHNvdXJjZS4KCjsKAgQBGjVSZWFsLXRpbWUgcG93ZXIgbWVhc3VyZW1lbnQgZnJvbSB0aGUgRFVUIHBvd2VyIHJhaWwuCgpLCgQGAAICGkNTdHJlYW0gcmVhbC10aW1lIHBvd2VyIG1lYXN1cmVtZW50cyBmcm9tIHRoZSB2aXJ0dWFsIHBvd2VyIHNvdXJjZS4KYgZwcm90bzM=
  drivers:
    - language: python
      package: jumpstarter-driver-power
      clientClass: "jumpstarter_driver_power.client.VirtualPowerClient"
