apiVersion: jumpstarter.dev/v1alpha1
kind: DriverInterface
metadata:
  name: dev-jumpstarter-corellium-v1
spec:
  proto:
    package: jumpstarter.interfaces.corellium.v1
    descriptor: Cg9jb3JlbGxpdW0ucHJvdG8SI2p1bXBzdGFydGVyLmludGVyZmFjZXMuY29yZWxsaXVtLnYxMgsKCUNvcmVsbGl1bUokCiIKAgYAGhxDb3JlbGxpdW0gdG9wLWxldmVsIGRyaXZlci4KYgZwcm90bzM=
  drivers:
    - language: python
      package: jumpstarter-driver-corellium
      clientClass: "jumpstarter_driver_corellium.client.CorelliumClient"
