[project]
name = "jumpstarter-driver-http"
dynamic = ["version", "dependencies"]
description = "Exporter HTTP service driver"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Benny Zlotnik", email = "bzlotnik@redhat.com" }]
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter=={{ version }}",
    "jumpstarter-driver-composite=={{ version }}",
    "jumpstarter-driver-opendal=={{ version }}",
    "yarl>=1.18.3",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["src"]

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.0.0",
    "pytest-asyncio>=0.24.0",
]

