# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qemu.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qemu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nqemu.proto\x12\x1ejumpstarter.interfaces.qemu.v1\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x13GetHostnameResponse\x12\r\n\x05value\x18\x01 \x01(\t\"$\n\x13GetPasswordResponse\x12\r\n\x05value\x18\x01 \x01(\t\"$\n\x13GetUsernameResponse\x12\r\n\x05value\x18\x01 \x01(\t\"\"\n\x12SetDiskSizeRequest\x12\x0c\n\x04size\x18\x01 \x01(\t\"$\n\x14SetMemorySizeRequest\x12\x0c\n\x04size\x18\x01 \x01(\t2\xd4\x03\n\x04Qemu\x12Z\n\x0bGetHostname\x12\x16.google.protobuf.Empty\x1a\x33.jumpstarter.interfaces.qemu.v1.GetHostnameResponse\x12Z\n\x0bGetPassword\x12\x16.google.protobuf.Empty\x1a\x33.jumpstarter.interfaces.qemu.v1.GetPasswordResponse\x12Z\n\x0bGetUsername\x12\x16.google.protobuf.Empty\x1a\x33.jumpstarter.interfaces.qemu.v1.GetUsernameResponse\x12Y\n\x0bSetDiskSize\x12\x32.jumpstarter.interfaces.qemu.v1.SetDiskSizeRequest\x1a\x16.google.protobuf.Empty\x12]\n\rSetMemorySize\x12\x34.jumpstarter.interfaces.qemu.v1.SetMemorySizeRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qemu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETHOSTNAMERESPONSE']._serialized_start=75
  _globals['_GETHOSTNAMERESPONSE']._serialized_end=111
  _globals['_GETPASSWORDRESPONSE']._serialized_start=113
  _globals['_GETPASSWORDRESPONSE']._serialized_end=149
  _globals['_GETUSERNAMERESPONSE']._serialized_start=151
  _globals['_GETUSERNAMERESPONSE']._serialized_end=187
  _globals['_SETDISKSIZEREQUEST']._serialized_start=189
  _globals['_SETDISKSIZEREQUEST']._serialized_end=223
  _globals['_SETMEMORYSIZEREQUEST']._serialized_start=225
  _globals['_SETMEMORYSIZEREQUEST']._serialized_end=261
  _globals['_QEMU']._serialized_start=264
  _globals['_QEMU']._serialized_end=732
# @@protoc_insertion_point(module_scope)
