# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import qemu_pb2 as qemu__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qemu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QemuStub(object):
    """Qemu(*, uuid: uuid.UUID = <factory>, labels: dict[str, str] = <factory>, children: 'dict[str, Driver]' = <factory>, description: 'str | None' = None, methods_description: 'dict[str, str]' = <factory>, log_level: 'str' = 'INFO')
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHostname = channel.unary_unary(
                '/jumpstarter.interfaces.qemu.v1.Qemu/GetHostname',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=qemu__pb2.GetHostnameResponse.FromString,
                _registered_method=True)
        self.GetPassword = channel.unary_unary(
                '/jumpstarter.interfaces.qemu.v1.Qemu/GetPassword',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=qemu__pb2.GetPasswordResponse.FromString,
                _registered_method=True)
        self.GetUsername = channel.unary_unary(
                '/jumpstarter.interfaces.qemu.v1.Qemu/GetUsername',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=qemu__pb2.GetUsernameResponse.FromString,
                _registered_method=True)
        self.SetDiskSize = channel.unary_unary(
                '/jumpstarter.interfaces.qemu.v1.Qemu/SetDiskSize',
                request_serializer=qemu__pb2.SetDiskSizeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetMemorySize = channel.unary_unary(
                '/jumpstarter.interfaces.qemu.v1.Qemu/SetMemorySize',
                request_serializer=qemu__pb2.SetMemorySizeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class QemuServicer(object):
    """Qemu(*, uuid: uuid.UUID = <factory>, labels: dict[str, str] = <factory>, children: 'dict[str, Driver]' = <factory>, description: 'str | None' = None, methods_description: 'dict[str, str]' = <factory>, log_level: 'str' = 'INFO')
    """

    def GetHostname(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDiskSize(self, request, context):
        """Set the disk size for resizing before boot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMemorySize(self, request, context):
        """Set the memory size for next boot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QemuServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHostname': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostname,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=qemu__pb2.GetHostnameResponse.SerializeToString,
            ),
            'GetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPassword,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=qemu__pb2.GetPasswordResponse.SerializeToString,
            ),
            'GetUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsername,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=qemu__pb2.GetUsernameResponse.SerializeToString,
            ),
            'SetDiskSize': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDiskSize,
                    request_deserializer=qemu__pb2.SetDiskSizeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetMemorySize': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMemorySize,
                    request_deserializer=qemu__pb2.SetMemorySizeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jumpstarter.interfaces.qemu.v1.Qemu', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jumpstarter.interfaces.qemu.v1.Qemu', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Qemu(object):
    """Qemu(*, uuid: uuid.UUID = <factory>, labels: dict[str, str] = <factory>, children: 'dict[str, Driver]' = <factory>, description: 'str | None' = None, methods_description: 'dict[str, str]' = <factory>, log_level: 'str' = 'INFO')
    """

    @staticmethod
    def GetHostname(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.qemu.v1.Qemu/GetHostname',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            qemu__pb2.GetHostnameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.qemu.v1.Qemu/GetPassword',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            qemu__pb2.GetPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.qemu.v1.Qemu/GetUsername',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            qemu__pb2.GetUsernameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDiskSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.qemu.v1.Qemu/SetDiskSize',
            qemu__pb2.SetDiskSizeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMemorySize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.qemu.v1.Qemu/SetMemorySize',
            qemu__pb2.SetMemorySizeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
