[project]
name = "jumpstarter-driver-tftp"
dynamic = ["version", "dependencies"]
description = "Add your description here"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Benny Zlotnik", email = "bzlotnik@redhat.com" }]
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter=={{ version }}",
    "jumpstarter-driver-composite=={{ version }}",
    "jumpstarter-driver-opendal=={{ version }}",
]

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=6.0.0",
    "pytest-anyio>=0.0.0",
    "pytest-asyncio>=0.0.0",
    "jumpstarter-testing",
]


[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_tftp"]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

