/*
Copyright 2026. The Jumpstarter Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package e2e

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"sync"
	"time"
)

const (
	dexIssuerURL = "https://dex.dex.svc.cluster.local:5556"
	dexClientID  = "jumpstarter-cli"
	dexAudience  = "jumpstarter-cli"
	// DexTestPassword is the bcrypt-encoded password shared by every
	// staticPassword in dex.values.yaml.
	DexTestPassword = "password"
)

// dexDiscovery is the subset of OIDC discovery fields we need to fetch a
// token via the password grant.
type dexDiscovery struct {
	Issuer        string `json:"issuer"`
	TokenEndpoint string `json:"token_endpoint"`
}

// dexTokenResponse is the subset of the Dex token response we care about.
type dexTokenResponse struct {
	IDToken     string `json:"id_token"`
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
}

var (
	tokenCacheMu sync.Mutex
	tokenCache   = map[string]cachedToken{}
)

type cachedToken struct {
	idToken string
	expiry  time.Time
}

// dexHTTPClient returns an http.Client whose root CA pool includes the
// CA generated by setup-e2e.sh. SSL_CERT_FILE is set by run-e2e.sh to
// point at $REPO_ROOT/ca.pem. If the cert cannot be loaded the client
// falls back to InsecureSkipVerify=true so unit-test runs that lack the
// cluster don't hard-fail at module init time.
func dexHTTPClient() *http.Client {
	tlsConfig := &tls.Config{MinVersion: tls.VersionTLS12}

	if path := os.Getenv("SSL_CERT_FILE"); path != "" {
		if pem, err := os.ReadFile(path); err == nil {
			pool := x509.NewCertPool()
			if pool.AppendCertsFromPEM(pem) {
				tlsConfig.RootCAs = pool
			}
		}
	}
	if tlsConfig.RootCAs == nil {
		tlsConfig.InsecureSkipVerify = true
	}

	return &http.Client{
		Timeout:   30 * time.Second,
		Transport: &http.Transport{TLSClientConfig: tlsConfig},
	}
}

// fetchDexDiscovery loads the OIDC discovery document for the Dex
// instance deployed by setup-e2e.sh.
func fetchDexDiscovery(ctx context.Context, client *http.Client) (dexDiscovery, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		dexIssuerURL+"/.well-known/openid-configuration", nil)
	if err != nil {
		return dexDiscovery{}, err
	}
	resp, err := client.Do(req)
	if err != nil {
		return dexDiscovery{}, fmt.Errorf("fetching dex discovery: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return dexDiscovery{}, fmt.Errorf("dex discovery returned %d: %s",
			resp.StatusCode, string(body))
	}
	var d dexDiscovery
	if err := json.NewDecoder(resp.Body).Decode(&d); err != nil {
		return dexDiscovery{}, fmt.Errorf("decoding dex discovery: %w", err)
	}
	if d.TokenEndpoint == "" {
		return dexDiscovery{}, fmt.Errorf("dex discovery missing token_endpoint")
	}
	return d, nil
}

// DexToken returns a Dex-issued id_token for the given username/password.
// Tokens are cached in-process for ~30 minutes so the suite doesn't pay
// the discovery + password-grant round trip on every spec.
//
// The username is the short form configured in dex.values.yaml (e.g.
// "dev-alice"); Dex's `local` password connector keys on email, so the
// helper appends "@example.com" before sending the request. The
// controller sees the OIDC subject as "dex:<username>" because of the
// claimMappings.username.prefix in e2e/values.kind.yaml.
func DexToken(ctx context.Context, username, password string) (string, error) {
	tokenCacheMu.Lock()
	if cached, ok := tokenCache[username]; ok && time.Now().Before(cached.expiry) {
		tokenCacheMu.Unlock()
		return cached.idToken, nil
	}
	tokenCacheMu.Unlock()

	client := dexHTTPClient()
	disc, err := fetchDexDiscovery(ctx, client)
	if err != nil {
		return "", err
	}

	loginID := username
	if !strings.Contains(loginID, "@") {
		loginID += "@example.com"
	}

	form := url.Values{}
	form.Set("grant_type", "password")
	form.Set("client_id", dexClientID)
	form.Set("username", loginID)
	form.Set("password", password)
	form.Set("scope", "openid profile email audience:server:client_id:"+dexAudience)

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, disc.TokenEndpoint,
		strings.NewReader(form.Encode()))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("dex token request: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("dex token request failed (%d): %s",
			resp.StatusCode, string(body))
	}
	var tr dexTokenResponse
	if err := json.Unmarshal(body, &tr); err != nil {
		return "", fmt.Errorf("decoding dex token response: %w", err)
	}
	if tr.IDToken == "" {
		return "", fmt.Errorf("dex token response missing id_token: %s", string(body))
	}

	ttl := time.Duration(tr.ExpiresIn) * time.Second
	if ttl <= 0 {
		ttl = time.Hour
	}
	if ttl > 30*time.Minute {
		ttl = 30 * time.Minute
	}

	tokenCacheMu.Lock()
	tokenCache[username] = cachedToken{idToken: tr.IDToken, expiry: time.Now().Add(ttl)}
	tokenCacheMu.Unlock()

	return tr.IDToken, nil
}

// DecodeJWTClaims parses the unverified payload of a JWT for inspection.
// Used in tests to assert claim values (e.g. iss) on bootstrap tokens
// returned by CreateClient/CreateExporter; never use it for trust
// decisions — the controller does that on its end.
func DecodeJWTClaims(token string) (map[string]any, error) {
	parts := strings.Split(token, ".")
	if len(parts) < 2 {
		return nil, fmt.Errorf("malformed jwt: %d segments", len(parts))
	}
	raw, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return nil, fmt.Errorf("decode jwt payload: %w", err)
	}
	var claims map[string]any
	if err := json.Unmarshal(raw, &claims); err != nil {
		return nil, fmt.Errorf("unmarshal jwt payload: %w", err)
	}
	return claims, nil
}
