# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import probe_rs_pb2 as probe__rs__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in probe_rs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProbeRsStub(object):
    """probe-rs driver for Jumpstarter
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Download = channel.unary_unary(
                '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Download',
                request_serializer=probe__rs__pb2.DownloadRequest.SerializeToString,
                response_deserializer=probe__rs__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.Erase = channel.unary_unary(
                '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Erase',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=probe__rs__pb2.EraseResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Info',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=probe__rs__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Read',
                request_serializer=probe__rs__pb2.ReadRequest.SerializeToString,
                response_deserializer=probe__rs__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.ResetTarget = channel.unary_unary(
                '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/ResetTarget',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=probe__rs__pb2.ResetTargetResponse.FromString,
                _registered_method=True)


class ProbeRsServicer(object):
    """probe-rs driver for Jumpstarter
    """

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Erase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProbeRsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Download': grpc.unary_unary_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=probe__rs__pb2.DownloadRequest.FromString,
                    response_serializer=probe__rs__pb2.DownloadResponse.SerializeToString,
            ),
            'Erase': grpc.unary_unary_rpc_method_handler(
                    servicer.Erase,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=probe__rs__pb2.EraseResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=probe__rs__pb2.InfoResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=probe__rs__pb2.ReadRequest.FromString,
                    response_serializer=probe__rs__pb2.ReadResponse.SerializeToString,
            ),
            'ResetTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetTarget,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=probe__rs__pb2.ResetTargetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jumpstarter.interfaces.probe_rs.v1.ProbeRs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jumpstarter.interfaces.probe_rs.v1.ProbeRs', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProbeRs(object):
    """probe-rs driver for Jumpstarter
    """

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Download',
            probe__rs__pb2.DownloadRequest.SerializeToString,
            probe__rs__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Erase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Erase',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            probe__rs__pb2.EraseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Info',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            probe__rs__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/Read',
            probe__rs__pb2.ReadRequest.SerializeToString,
            probe__rs__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jumpstarter.interfaces.probe_rs.v1.ProbeRs/ResetTarget',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            probe__rs__pb2.ResetTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
