[project]
name = "jumpstarter-driver-qemu"
dynamic = ["version", "urls"]
description = ""
authors = [
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
  "jumpstarter",
  "jumpstarter-driver-composite",
  "jumpstarter-driver-network",
  "jumpstarter-driver-opendal",
  "jumpstarter-driver-power",
  "jumpstarter-driver-pyserial",
  "pyyaml>=6.0.2",
  "qemu-qmp>=0.0.3",
]

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "requests>=2.32.3"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[tool.uv.sources]
jumpstarter-driver-opendal = { workspace = true }
jumpstarter-driver-composite = { workspace = true }
jumpstarter-driver-network = { workspace = true }
jumpstarter-driver-pyserial = { workspace = true }
jumpstarter-driver-power = { workspace = true }

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
