[project]
name = "jumpstarter-driver-qemu"
dynamic = ["version", "dependencies"]
description = ""
authors = [
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"

[tool.hatch.metadata.hooks.uv-dynamic-versioning]
dependencies = [
  "jumpstarter=={{ version }}",
  "jumpstarter-driver-composite=={{ version }}",
  "jumpstarter-driver-network=={{ version }}",
  "jumpstarter-driver-opendal=={{ version }}",
  "jumpstarter-driver-power=={{ version }}",
  "jumpstarter-driver-pyserial=={{ version }}",
  "pyyaml>=6.0.2",
  "qemu-qmp>=0.0.3",
]

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "requests>=2.32.3"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv.sources]
jumpstarter-driver-opendal = { workspace = true }
jumpstarter-driver-composite = { workspace = true }
jumpstarter-driver-network = { workspace = true }
jumpstarter-driver-pyserial = { workspace = true }
jumpstarter-driver-power = { workspace = true }

[build-system]
requires = ["hatchling",  "uv-dynamic-versioning"]
build-backend = "hatchling.build"

