apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: dutlink
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  dutlink:
    type: jumpstarter_driver_dutlink.driver.Dutlink
    config: null
