apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  name: ssh-mitm
  namespace: default
endpoint: grpc.jumpstarter.example.com:443
token: xxxxx
export:
  ssh_mitm:
    type: jumpstarter_driver_ssh.driver.SSHWrapper
    config:
      default_username: root
    children:
      tcp:
        type: jumpstarter_driver_ssh_mitm.driver.SSHMITM
        config:
          ssh_identity_file: /path/to/private/key
          default_username: root
        children:
          tcp:
            type: jumpstarter_driver_network.driver.TcpNetwork
            config:
              host: 192.168.1.100
              port: 22
