apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  namespace: default
  name: ssh-mitm-example
export:
  ssh_mitm:
    type: jumpstarter_driver_ssh_mitm.driver.SSHMITM
    config:
      default_username: "root"
      # Option 1: Provide SSH key directly in config
      ssh_identity: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAFwAAAAdz
        c2gtcnNhAAAAAwEAAQAAAQEAy... (your private key here)
        -----END OPENSSH PRIVATE KEY-----
      # Option 2: Or provide path to key file (uncomment to use)
      # ssh_identity_file: "/path/to/your/private/key"
    children:
      tcp:
        type: jumpstarter_driver_network.driver.TcpNetwork
        config:
          host: "192.168.1.100"
          port: 22
