name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ruff
        uses: astral-sh/ruff-action@84f83ecf9e1e15d26b7984c7ec9cf73d39ffc946 # v3.3.1
        with:
          version-file: pyproject.toml
